//! Rust models from the same catalog as REST and TypeScript. No DB connection at build time.
use crate::catalog::{Catalog, Column, TableKind};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write,
};

fn literal(value: &str) -> String {
    // JSON escaping differs from Rust for control characters; use Rust's Debug string escaping.
    format!("{value:?}")
}

fn ident(value: &str) -> String {
    let mut out = String::new();
    for c in value.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c.to_ascii_lowercase());
        } else {
            let _ = write!(out, "_u{:x}_", c as u32);
        }
    }
    if out.is_empty() || out == "_" {
        out = "unnamed".into();
    }
    if out.as_bytes()[0].is_ascii_digit() {
        out.insert(0, '_');
    }
    if ["self", "super", "crate"].contains(&out.as_str()) {
        out.insert_str(0, "field_");
    }
    if [
        "as", "async", "await", "break", "const", "continue", "dyn", "else", "enum", "extern",
        "false", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "static", "struct", "trait", "true", "type", "unsafe",
        "use", "where", "while", "abstract", "become", "box", "do", "final", "macro", "override",
        "priv", "try", "typeof", "unsized", "virtual", "yield",
    ]
    .contains(&out.as_str())
    {
        out.insert_str(0, "r#");
    }
    out
}

fn unique(base: String, used: &mut BTreeSet<String>) -> String {
    let mut name = base.clone();
    let mut n = 2;
    while !used.insert(name.clone()) {
        name = format!("{base}_{n}");
        n += 1;
    }
    name
}

fn variant(value: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in value.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(if upper { c.to_ascii_uppercase() } else { c });
            upper = false;
        } else {
            upper = true;
        }
    }
    if out.is_empty() || out == "Self" || out.as_bytes()[0].is_ascii_digit() {
        out.insert_str(0, "Value");
    }
    out
}

fn scalar(name: &str) -> String {
    if let Some(element) = name.strip_suffix("[]") {
        return format!("Vec<Option<{}>>", scalar(element));
    }
    match name {
        "smallint" => "i16",
        "integer" => "i32",
        "bigint" => "i64",
        "oid" => "u32",
        "real" => "f32",
        "double precision" => "f64",
        "numeric" => "serde_json::Number",
        "boolean" => "bool",
        "json" | "jsonb" | "record" => "serde_json::Value",
        "void" => "()",
        _ => "String",
    }
    .into()
}

fn column_type(column: &Column, enums: &BTreeMap<String, String>) -> String {
    if let Some(name) = enums.get(&column.name) {
        if column.category == 'A' {
            format!("Vec<Option<{name}>>")
        } else {
            name.clone()
        }
    } else {
        scalar(&column.type_name)
    }
}

/// Generate a self-contained Rust module using serde, serde_json and nelcota-client.
/// Dates, UUIDs and unknown scalar types remain strings. Numeric keeps decimal precision.
pub fn generate(catalog: &Catalog) -> String {
    let mut out = String::from(
        "// Generated by `nelcota types --lang rust`. Do not edit by hand.\n// Requires serde (derive), serde_json and nelcota-client.\n\n",
    );
    let _ = writeln!(out, "pub mod {} {{", ident(&catalog.schema));
    let mut used = BTreeSet::from(["rpc".into()]);
    let modules: BTreeMap<_, _> = catalog
        .tables
        .keys()
        .map(|name| (name.clone(), unique(ident(name), &mut used)))
        .collect();
    for table in catalog.tables.values() {
        let _ = writeln!(out, "    pub mod {} {{", modules[&table.name]);
        let _ = writeln!(
            out,
            "        pub const NAME: &str = {};",
            literal(&table.name)
        );
        let pk = table
            .primary_key
            .iter()
            .map(|s| literal(s))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "        pub const PRIMARY_KEY: &[&str] = &[{pk}];");
        let mut enum_names = BTreeMap::new();
        for (index, column) in table
            .columns
            .iter()
            .enumerate()
            .filter(|(_, c)| !c.enum_values.is_empty())
        {
            let name = format!("EnumColumn{index}");
            enum_names.insert(column.name.clone(), name.clone());
            out.push_str("        #[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]\n");
            let _ = writeln!(out, "        pub enum {name} {{");
            let mut variants = BTreeSet::new();
            for value in &column.enum_values {
                let base = variant(value);
                let mut variant = base.clone();
                let mut n = 2;
                while !variants.insert(variant.clone()) {
                    variant = format!("{base}{n}");
                    n += 1;
                }
                let _ = writeln!(
                    out,
                    "            #[serde(rename = {})]\n            {variant},",
                    literal(value)
                );
            }
            out.push_str("        }\n");
        }
        let mut used_fields = BTreeSet::new();
        let fields: BTreeMap<_, _> = table
            .columns
            .iter()
            .map(|c| (c.name.clone(), unique(ident(&c.name), &mut used_fields)))
            .collect();
        for mode in ["Row", "Insert", "Update"] {
            if mode != "Row" && table.kind == TableKind::MaterializedView {
                continue;
            }
            let columns: Vec<_> = table
                .columns
                .iter()
                .filter(|c| mode == "Row" || !c.generated)
                .collect();
            let all_optional = mode == "Update"
                || (mode == "Insert" && columns.iter().all(|c| c.nullable || c.has_default));
            let default = if all_optional { ", Default" } else { "" };
            let _ = writeln!(
                out,
                "        #[derive(Clone, Debug, serde::Serialize, serde::Deserialize{default})]\n        pub struct {mode} {{"
            );
            for column in columns {
                let base = column_type(column, &enum_names);
                let base = if column.nullable {
                    format!("Option<{base}>")
                } else {
                    base
                };
                let optional = mode == "Update"
                    || (mode == "Insert" && (column.nullable || column.has_default));
                let _ = writeln!(
                    out,
                    "            #[serde(rename = {})]",
                    literal(&column.name)
                );
                if optional {
                    out.push_str("            #[serde(default, skip_serializing_if = \"nelcota_client::Field::is_omitted\")]\n");
                }
                let ty = if optional {
                    format!("nelcota_client::Field<{base}>")
                } else {
                    base
                };
                let _ = writeln!(out, "            pub {}: {ty},", fields[&column.name]);
            }
            out.push_str("        }\n");
        }
        out.push_str("    }\n");
    }
    out.push_str("    pub mod rpc {\n");
    let mut used = BTreeSet::new();
    for (name, overloads) in &catalog.functions {
        for (index, function) in overloads.iter().enumerate() {
            let base = if overloads.len() > 1 {
                format!("{}_{}", ident(name), index + 1)
            } else {
                ident(name)
            };
            let module = unique(base, &mut used);
            let _ = writeln!(
                out,
                "        pub mod {module} {{\n            pub const NAME: &str = {};",
                literal(name)
            );
            let default = if function.args.iter().all(|a| a.has_default) {
                ", Default"
            } else {
                ""
            };
            let _ = writeln!(
                out,
                "            #[derive(Clone, Debug, serde::Serialize, serde::Deserialize{default})]\n            pub struct Args {{"
            );
            let mut used = BTreeSet::new();
            for arg in &function.args {
                let name = unique(ident(&arg.name), &mut used);
                let _ = writeln!(
                    out,
                    "                #[serde(rename = {})]",
                    literal(&arg.name)
                );
                let ty = format!("Option<{}>", scalar(&arg.type_name));
                let ty = if arg.has_default {
                    out.push_str("                #[serde(default, skip_serializing_if = \"nelcota_client::Field::is_omitted\")]\n");
                    format!("nelcota_client::Field<{ty}>")
                } else {
                    ty
                };
                let _ = writeln!(out, "                pub {name}: {ty},");
            }
            out.push_str("            }\n");
            let table_name = function
                .return_type
                .strip_prefix(&format!("{}.", catalog.schema))
                .unwrap_or(&function.return_type);
            let base = modules
                .get(table_name)
                .map(|m| format!("super::super::{m}::Row"))
                .unwrap_or_else(|| scalar(&function.return_type));
            let returns = if function.returns_void {
                "()".into()
            } else if function.returns_set {
                format!("Vec<Option<{base}>>")
            } else {
                format!("Option<{base}>")
            };
            let _ = writeln!(out, "            pub type Returns = {returns};\n        }}");
        }
    }
    out.push_str("    }\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn identifiers_and_precise_types() {
        assert_eq!(ident("type"), "r#type");
        assert_eq!(ident("Self"), "field_self");
        assert_eq!(ident("a-b"), "a_u2d_b");
        assert_eq!(scalar("numeric"), "serde_json::Number");
        assert_eq!(scalar("bigint[]"), "Vec<Option<i64>>");
        let mut used = BTreeSet::new();
        assert_eq!(unique(ident("A"), &mut used), "a");
        assert_eq!(unique(ident("a"), &mut used), "a_2");
        assert_eq!(literal("\u{001b}"), "\"\\u{1b}\"");
    }

    #[test]
    fn generated_models_fixture() {
        use crate::catalog::{Argument, Column, Function, Privileges, Table};
        let column = |name: &str, ty: &str, nullable, default, generated| Column {
            name: name.into(),
            type_name: ty.into(),
            full_type: ty.into(),
            category: 'N',
            element_type: None,
            enum_values: Vec::new(),
            nullable,
            has_default: default,
            generated,
            comment: None,
        };
        let mut mood = column("type", "public.mood", false, true, false);
        mood.enum_values = vec![
            "low".into(),
            "high-priority".into(),
            "high priority".into(),
            "Self".into(),
        ];
        let table = Table {
            name: "notes".into(),
            kind: TableKind::Table,
            columns: vec![
                column("id", "bigint", false, true, true),
                column("body", "text", false, false, false),
                column("extra", "jsonb", true, false, false),
                column("price", "numeric", false, true, false),
                column("tags", "text[]", false, true, false),
                mood,
                column("Self", "text", true, false, false),
                column("field_self", "text", true, false, false),
                column("x\u{001b}", "text", true, false, false),
            ],
            primary_key: vec!["id".into()],
            foreign_keys: vec![],
            rls_enabled: true,
            rls_forced: false,
            comment: None,
            privileges: [Privileges::default(); 3],
        };
        let function = Function {
            name: "add".into(),
            args: vec![
                Argument {
                    name: "a".into(),
                    type_name: "integer".into(),
                    has_default: false,
                },
                Argument {
                    name: "b".into(),
                    type_name: "integer".into(),
                    has_default: true,
                },
            ],
            return_type: "integer".into(),
            returns_set: false,
            returns_void: false,
            volatility: 'i',
            comment: None,
            executable: [true; 3],
        };
        let catalog = Catalog {
            schema: "public".into(),
            tables: BTreeMap::from([("notes".into(), table)]),
            functions: BTreeMap::from([("add".into(), vec![function])]),
        };
        let code = generate(&catalog);
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../sdk/rust/test/generated.rs");
        if std::env::var_os("NELCOTA_UPDATE_RUST_FIXTURE").is_some() {
            std::fs::write(&path, &code).unwrap();
        }
        assert_eq!(
            code,
            std::fs::read_to_string(path).expect("generated fixture exists")
        );
    }
}
