//! TypeScript types generated from the catalog (`nelcota types`).
//!
//! The shape (`Database[schema]["Tables"][t]["Row" | "Insert" | "Update"]`)
//! follows the convention the ecosystem already knows, but it is plain
//! TypeScript: it depends on no SDK. `Relationships` lists each table's foreign
//! keys inside the exposed schema, which is what a typed client needs to know
//! whether an embed is an object (this table has the key) or an array (the
//! other table points here).

use std::fmt::Write;

use crate::catalog::{Catalog, Column, Table, TableKind};

fn ts_scalar(type_name: &str) -> String {
    if let Some(element) = type_name.strip_suffix("[]") {
        return format!("{}[]", ts_scalar(element));
    }
    match type_name {
        "smallint" | "integer" | "bigint" | "real" | "double precision" | "numeric" | "oid" => {
            "number".into()
        }
        "boolean" => "boolean".into(),
        "json" | "jsonb" => "Json".into(),
        "void" => "undefined".into(),
        _ => "string".into(),
    }
}

fn ts_column(column: &Column) -> String {
    if !column.enum_values.is_empty() {
        let union = column
            .enum_values
            .iter()
            .map(|v| serde_json::to_string(v).unwrap_or_default())
            .collect::<Vec<_>>()
            .join(" | ");
        return if column.category == 'A' {
            format!("({union})[]")
        } else {
            union
        };
    }
    ts_scalar(&column.type_name)
}

fn key(name: &str) -> String {
    let simple = name
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if simple {
        name.to_owned()
    } else {
        serde_json::to_string(name).unwrap_or_default()
    }
}

/// A TypeScript string literal (JSON escaping is valid TypeScript).
fn string(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_default()
}

fn string_tuple(values: &[String]) -> String {
    let items = values.iter().map(|v| string(v)).collect::<Vec<_>>();
    format!("[{}]", items.join(", "))
}

fn relationships(out: &mut String, catalog: &Catalog, table: &Table) {
    let keys: Vec<_> = table
        .foreign_keys
        .iter()
        .filter(|fk| {
            fk.foreign_schema == catalog.schema && catalog.tables.contains_key(&fk.foreign_table)
        })
        .collect();
    if keys.is_empty() {
        out.push_str(
            "        Relationships: [];
",
        );
        return;
    }
    out.push_str(
        "        Relationships: [
",
    );
    for fk in keys {
        let _ = writeln!(
            out,
            "          {{ foreignKeyName: {}; columns: {}; referencedRelation: {}; referencedColumns: {} }},",
            string(&fk.name),
            string_tuple(&fk.columns),
            string(&fk.foreign_table),
            string_tuple(&fk.foreign_columns),
        );
    }
    out.push_str(
        "        ];
",
    );
}

pub fn generate(catalog: &Catalog) -> String {
    let mut out = String::new();
    let schema = key(&catalog.schema);
    out.push_str("// Generated by `nelcota types`. Do not edit by hand.\n\n");
    out.push_str(
        "export type Json =\n  | string\n  | number\n  | boolean\n  | null\n  | { [key: string]: Json | undefined }\n  | Json[];\n\n",
    );
    let _ = writeln!(out, "export interface Database {{\n  {schema}: {{");

    for (section, views) in [("Tables", false), ("Views", true)] {
        let _ = writeln!(out, "    {section}: {{");
        for table in catalog
            .tables
            .values()
            .filter(|t| (t.kind != TableKind::Table) == views)
        {
            let _ = writeln!(out, "      {}: {{", key(&table.name));
            out.push_str("        Row: {\n");
            for c in &table.columns {
                let null = if c.nullable { " | null" } else { "" };
                let _ = writeln!(out, "          {}: {}{null};", key(&c.name), ts_column(c));
            }
            out.push_str("        };\n");
            if table.kind != TableKind::MaterializedView {
                for (variant, all_optional) in [("Insert", false), ("Update", true)] {
                    let _ = writeln!(out, "        {variant}: {{");
                    for c in table.columns.iter().filter(|c| !c.generated) {
                        let optional = all_optional || c.nullable || c.has_default;
                        let null = if c.nullable { " | null" } else { "" };
                        let _ = writeln!(
                            out,
                            "          {}{}: {}{null};",
                            key(&c.name),
                            if optional { "?" } else { "" },
                            ts_column(c)
                        );
                    }
                    out.push_str("        };\n");
                }
            }
            relationships(&mut out, catalog, table);
            out.push_str("      };\n");
        }
        out.push_str("    };\n");
    }

    out.push_str("    Functions: {\n");
    for (name, overloads) in &catalog.functions {
        // Overloads become a union of signatures.
        let signatures: Vec<String> = overloads
            .iter()
            .map(|f| {
                let args = f
                    .args
                    .iter()
                    .map(|a| {
                        format!(
                            "{}{}: {}",
                            key(&a.name),
                            if a.has_default { "?" } else { "" },
                            ts_scalar(&a.type_name)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join("; ");
                let base = catalog
                    .tables
                    .get(
                        f.return_type
                            .trim_start_matches(&format!("{}.", catalog.schema)),
                    )
                    .map(|t| {
                        format!(
                            "Database[{}][\"Tables\"][{}][\"Row\"]",
                            string(&catalog.schema),
                            string(&t.name)
                        )
                    })
                    .unwrap_or_else(|| ts_scalar(&f.return_type));
                let returns = if f.returns_set {
                    format!("{base}[]")
                } else {
                    base
                };
                format!("{{ Args: {{ {args} }}; Returns: {returns} }}")
            })
            .collect();
        let _ = writeln!(out, "      {}: {};", key(name), signatures.join(" | "));
    }
    out.push_str("    };\n");

    out.push_str("    Enums: {\n");
    let mut enums: Vec<(String, &Vec<String>)> = Vec::new();
    for table in catalog.tables.values() {
        for c in table.columns.iter().filter(|c| !c.enum_values.is_empty()) {
            let name = c
                .type_name
                .trim_end_matches("[]")
                .rsplit('.')
                .next()
                .unwrap_or_default()
                .trim_matches('"')
                .to_owned();
            if !enums.iter().any(|(n, _)| n == &name) {
                enums.push((name, &c.enum_values));
            }
        }
    }
    for (name, values) in enums {
        let union = values
            .iter()
            .map(|v| serde_json::to_string(v).unwrap_or_default())
            .collect::<Vec<_>>()
            .join(" | ");
        let _ = writeln!(out, "      {}: {union};", key(&name));
    }
    out.push_str("    };\n  };\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::{Argument, ForeignKey, Function, Privileges};

    fn column(name: &str, type_name: &str) -> Column {
        Column {
            name: name.into(),
            type_name: type_name.into(),
            full_type: type_name.into(),
            category: 'N',
            element_type: None,
            enum_values: Vec::new(),
            nullable: false,
            has_default: false,
            generated: false,
            comment: None,
        }
    }

    fn table(name: &str, columns: Vec<Column>, foreign_keys: Vec<ForeignKey>) -> Table {
        Table {
            name: name.into(),
            kind: TableKind::Table,
            columns,
            primary_key: vec!["id".into()],
            foreign_keys,
            rls_enabled: true,
            rls_forced: false,
            comment: None,
            privileges: [Privileges::default(); 3],
        }
    }

    fn foreign_key(name: &str, column: &str, schema: &str, target: &str) -> ForeignKey {
        ForeignKey {
            name: name.into(),
            columns: vec![column.into()],
            foreign_schema: schema.into(),
            foreign_table: target.into(),
            foreign_columns: vec!["id".into()],
        }
    }

    fn shop(schema: &str) -> Catalog {
        let mut catalog = Catalog {
            schema: schema.into(),
            ..Catalog::default()
        };
        catalog.tables.insert(
            "customers".into(),
            table("customers", vec![column("id", "bigint")], Vec::new()),
        );
        catalog.tables.insert(
            "orders".into(),
            table(
                "orders",
                vec![column("id", "bigint"), column("customer_id", "bigint")],
                vec![
                    foreign_key(
                        "orders_customer_id_fkey",
                        "customer_id",
                        schema,
                        "customers",
                    ),
                    // Outside the exposed schema: not embeddable, not listed.
                    foreign_key("orders_audit_fkey", "id", "audit", "events"),
                ],
            ),
        );
        catalog.functions.insert(
            "recent_orders".into(),
            vec![Function {
                name: "recent_orders".into(),
                args: vec![Argument {
                    name: "since".into(),
                    type_name: "timestamptz".into(),
                    has_default: true,
                }],
                return_type: format!("{schema}.orders"),
                returns_set: true,
                returns_void: false,
                volatility: 's',
                comment: None,
                executable: [true; 3],
            }],
        );
        catalog
    }

    #[test]
    fn relationships_list_foreign_keys_inside_the_schema() {
        let out = generate(&shop("public"));
        assert!(
            out.contains(
                r#"{ foreignKeyName: "orders_customer_id_fkey"; columns: ["customer_id"]; referencedRelation: "customers"; referencedColumns: ["id"] },"#
            ),
            "{out}"
        );
        assert!(!out.contains("orders_audit_fkey"), "{out}");
        assert!(out.contains("Relationships: [];"), "{out}");
    }

    #[test]
    fn function_rows_refer_to_the_table_with_plain_string_keys() {
        let out = generate(&shop("public"));
        assert!(
            out.contains(r#"Returns: Database["public"]["Tables"]["orders"]["Row"][]"#),
            "{out}"
        );
        let out = generate(&shop("my-app"));
        assert!(out.contains(r#"  "my-app": {"#), "{out}");
        assert!(
            out.contains(r#"Returns: Database["my-app"]["Tables"]["orders"]["Row"][]"#),
            "{out}"
        );
    }
}
