//! Native PostgreSQL cluster configuration and removal.
use super::systemctl;
use crate::{
    project::run,
    scaffold,
    util::{ok, step},
};
use anyhow::Context;
use std::{fs, process::Command};
pub const POSTGRES_UNIT: &str = "postgresql@17-main";
pub const PG_DATA: &str = "/var/lib/postgresql/17/main";
const PG_CONF: &str = "/etc/postgresql/17/main/conf.d/nelcota.conf";

/// The Postgres profile as a `conf.d` file (the Debian packaging includes it).
pub fn render_postgres_conf(profile: &str) -> String {
    format!(
        "# Postgres profile {profile} for nelcota (generated by `nelcota init`).\n{}",
        scaffold::profile_settings(profile)
            .iter()
            .map(|(k, v)| format!("{k} = '{v}'\n"))
            .collect::<String>()
    )
}

/// The 17/main cluster with the profile and the `postgres` password the
/// app's `NELCOTA_DATABASE_URL` uses (over 127.0.0.1, scram-sha-256).
pub fn configure_postgres(profile: &str, password: &str) -> anyhow::Result<()> {
    step("Configuring Postgres 17");
    let clusters = Command::new("pg_lsclusters")
        .arg("--no-header")
        .output()
        .context("pg_lsclusters not found (is postgresql-17 installed?)")?;
    let exists = String::from_utf8_lossy(&clusters.stdout)
        .lines()
        .any(|l| l.split_whitespace().take(2).eq(["17", "main"]));
    if !exists {
        run(
            Command::new("pg_createcluster").args(["17", "main"]),
            "pg_createcluster",
        )?;
    }
    fs::write(PG_CONF, render_postgres_conf(profile))?;
    systemctl(&["enable".into(), POSTGRES_UNIT.into()])?;
    systemctl(&["restart".into(), POSTGRES_UNIT.into()])?;
    // Alphanumeric (util::secret): safe inside the literal.
    run(
        Command::new("runuser").args([
            "-u",
            "postgres",
            "--",
            "psql",
            "-q",
            "-c",
            &format!("ALTER ROLE postgres PASSWORD '{password}'"),
        ]),
        "setting the postgres password",
    )?;
    ok(&format!("cluster 17/main with the {profile} profile"));
    Ok(())
}

pub(super) fn remove_cluster() -> anyhow::Result<()> {
    run(
        Command::new("pg_dropcluster").args(["17", "main", "--stop"]),
        "pg_dropcluster",
    )
}
