//! Systemd unit rendering and service commands.
use super::{APP_LISTEN, POSTGRES_UNIT, deployed_binary};
use crate::{
    project::{Project, run},
    util::ok,
};
use anyhow::bail;
use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

pub fn app_unit(project: &str) -> String {
    format!("nelcota-{project}")
}

// Paths on the Linux machine, spelled with `/` whatever compiles the CLI.

pub fn unit_path(project: &str) -> PathBuf {
    PathBuf::from(format!("/etc/systemd/system/{}.service", app_unit(project)))
}

pub fn systemctl(args: &[String]) -> anyhow::Result<()> {
    run(
        Command::new("systemctl").args(args),
        &format!("systemctl {}", args.join(" ")),
    )
}

pub fn systemctl_quiet(args: &[String]) -> anyhow::Result<()> {
    let status = Command::new("systemctl")
        .args(args)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()?;
    if !status.success() {
        bail!("systemctl {} failed", args.join(" "));
    }
    Ok(())
}

/// `active`, `inactive`, `failed`, `activating`...; `None` without systemd.
pub fn unit_state(unit: &str) -> Option<String> {
    let output = Command::new("systemctl")
        .args(["is-active", unit])
        .output()
        .ok()?;
    let state = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    (!state.is_empty()).then_some(state)
}

/// The app's unit: this binary as `serve`, the project's `.env`, a
/// throwaway system user and no write access anywhere.
pub fn render_unit(project: &str, env_file: &Path) -> String {
    format!(
        "# nelcota project \"{project}\". Generated by `nelcota init`.\n\
         [Unit]\n\
         Description=nelcota ({project})\n\
         After=network-online.target {POSTGRES_UNIT}.service\n\
         Wants=network-online.target\n\
         Requires={POSTGRES_UNIT}.service\n\
         \n\
         [Service]\n\
         ExecStart={binary} serve\n\
         EnvironmentFile={env}\n\
         Environment=NELCOTA_LISTEN={APP_LISTEN}\n\
         Environment=NELCOTA_TRUST_PROXY=true\n\
         Environment=NELCOTA_PROJECT_NAME={project}\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         DynamicUser=yes\n\
         StateDirectory=nelcota-{project}\n\
         CapabilityBoundingSet=\n\
         NoNewPrivileges=yes\n\
         ProtectSystem=strict\n\
         ProtectHome=yes\n\
         PrivateTmp=yes\n\
         PrivateDevices=yes\n\
         ProtectKernelTunables=yes\n\
         ProtectKernelModules=yes\n\
         ProtectControlGroups=yes\n\
         RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX\n\
         LockPersonality=yes\n\
         MemoryDenyWriteExecute=yes\n\
         SystemCallArchitectures=native\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n",
        binary = deployed_binary().display(),
        env = env_file.display(),
    )
}

/// The app's unit file and systemd's view of it.
pub fn install_unit(project: &Project) -> anyhow::Result<()> {
    fs::write(
        unit_path(&project.name),
        render_unit(&project.name, &project.path(".env")),
    )?;
    systemctl(&["daemon-reload".into()])?;
    ok(&format!("unit {}.service", app_unit(&project.name)));
    Ok(())
}

pub(super) fn remove_unit(project: &Project) -> anyhow::Result<()> {
    let _ = systemctl_quiet(&["disable".into(), "--now".into(), app_unit(&project.name)]);
    let _ = fs::remove_file(unit_path(&project.name));
    systemctl(&["daemon-reload".into()])
}
