// Generated by `nelcota types --lang rust`. Do not edit by hand.
// Requires serde (derive), serde_json and nelcota-client.

pub mod public {
    pub mod notes {
        pub const NAME: &str = "notes";
        pub const PRIMARY_KEY: &[&str] = &["id"];
        #[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
        pub enum EnumColumn5 {
            #[serde(rename = "low")]
            Low,
            #[serde(rename = "high-priority")]
            HighPriority,
            #[serde(rename = "high priority")]
            HighPriority2,
            #[serde(rename = "Self")]
            ValueSelf,
        }
        #[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
        pub struct Row {
            #[serde(rename = "id")]
            pub id: i64,
            #[serde(rename = "body")]
            pub body: String,
            #[serde(rename = "extra")]
            pub extra: Option<serde_json::Value>,
            #[serde(rename = "price")]
            pub price: serde_json::Number,
            #[serde(rename = "tags")]
            pub tags: Vec<Option<String>>,
            #[serde(rename = "type")]
            pub r#type: EnumColumn5,
            #[serde(rename = "Self")]
            pub field_self: Option<String>,
            #[serde(rename = "field_self")]
            pub field_self_2: Option<String>,
            #[serde(rename = "x\u{1b}")]
            pub x_u1b_: Option<String>,
        }
        #[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
        pub struct Insert {
            #[serde(rename = "body")]
            pub body: String,
            #[serde(rename = "extra")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub extra: nelcota_client::Field<Option<serde_json::Value>>,
            #[serde(rename = "price")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub price: nelcota_client::Field<serde_json::Number>,
            #[serde(rename = "tags")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub tags: nelcota_client::Field<Vec<Option<String>>>,
            #[serde(rename = "type")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub r#type: nelcota_client::Field<EnumColumn5>,
            #[serde(rename = "Self")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub field_self: nelcota_client::Field<Option<String>>,
            #[serde(rename = "field_self")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub field_self_2: nelcota_client::Field<Option<String>>,
            #[serde(rename = "x\u{1b}")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub x_u1b_: nelcota_client::Field<Option<String>>,
        }
        #[derive(Clone, Debug, serde::Serialize, serde::Deserialize, Default)]
        pub struct Update {
            #[serde(rename = "body")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub body: nelcota_client::Field<String>,
            #[serde(rename = "extra")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub extra: nelcota_client::Field<Option<serde_json::Value>>,
            #[serde(rename = "price")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub price: nelcota_client::Field<serde_json::Number>,
            #[serde(rename = "tags")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub tags: nelcota_client::Field<Vec<Option<String>>>,
            #[serde(rename = "type")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub r#type: nelcota_client::Field<EnumColumn5>,
            #[serde(rename = "Self")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub field_self: nelcota_client::Field<Option<String>>,
            #[serde(rename = "field_self")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub field_self_2: nelcota_client::Field<Option<String>>,
            #[serde(rename = "x\u{1b}")]
            #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
            pub x_u1b_: nelcota_client::Field<Option<String>>,
        }
    }
    pub mod rpc {
        pub mod add {
            pub const NAME: &str = "add";
            #[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
            pub struct Args {
                #[serde(rename = "a")]
                pub a: Option<i32>,
                #[serde(rename = "b")]
                #[serde(default, skip_serializing_if = "nelcota_client::Field::is_omitted")]
                pub b: nelcota_client::Field<Option<i32>>,
            }
            pub type Returns = Option<i32>;
        }
    }
}
