#!/usr/bin/env node
// Runs the contract tests against the real binary: Postgres 17 and Mailpit in
// throwaway containers, `nelcota serve` on a free port, the fixture schema,
// types generated by `nelcota types`, then `vitest --project contract`.
//
//   cargo build -p nelcota-server && node scripts/contract.mjs
//
// NELCOTA_BIN points at another binary; --keep leaves everything running;
// --browser also builds the package and runs test/browser/smoke.mjs in Chromium.

import { spawn, spawnSync } from 'node:child_process';
import { createHmac } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(root, '../..');
const keep = process.argv.includes('--keep');
const browser = process.argv.includes('--browser');
const vitestArgs = process.argv.slice(2).filter((a) => a !== '--keep' && a !== '--browser');
const exe = process.platform === 'win32' ? 'nelcota.exe' : 'nelcota';
const bin = process.env.NELCOTA_BIN ?? join(repo, 'target', 'debug', exe);

const PG = 'nelcota-sdk-postgres';
const MAIL = 'nelcota-sdk-mailpit';
const PG_PORT = 54329;
const API_PORT = 8031;
const SMTP_PORT = 10259;
const MAIL_PORT = 18025;
const JWT_SECRET = 'sdk-contract-secret-with-more-than-32-characters';

function run(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: 'inherit', ...options });
  if (result.status !== 0) throw new Error(`${command} ${args.join(' ')} exited with ${result.status}`);
  return result;
}

function docker(...args) {
  return spawnSync('docker', args, { encoding: 'utf8' });
}

async function waitFor(what, check, seconds = 60) {
  const deadline = Date.now() + seconds * 1000;
  while (Date.now() < deadline) {
    if (await check()) return;
    await new Promise((r) => setTimeout(r, 300));
  }
  throw new Error(`${what} did not come up in ${seconds}s`);
}

if (!existsSync(bin)) {
  console.error(`No binary at ${bin}: run \`cargo build -p nelcota-server\` or set NELCOTA_BIN.`);
  process.exit(1);
}

const storageDir = mkdtempSync(join(tmpdir(), 'nelcota-sdk-storage-'));
let server;

function teardown() {
  if (keep) return;
  server?.kill();
  docker('rm', '-f', PG, MAIL);
  rmSync(storageDir, { recursive: true, force: true });
}

process.on('SIGINT', () => {
  teardown();
  process.exit(130);
});

let status = 1;
try {
  docker('rm', '-f', PG, MAIL);
  run('docker', ['run', '-d', '--name', PG, '-e', 'POSTGRES_PASSWORD=postgres', '-p', `127.0.0.1:${PG_PORT}:5432`, 'postgres:17-alpine']);
  run('docker', ['run', '-d', '--name', MAIL, '-p', `127.0.0.1:${SMTP_PORT}:1025`, '-p', `127.0.0.1:${MAIL_PORT}:8025`, 'axllent/mailpit:v1.27.0']);
  await waitFor('Postgres', () => docker('exec', PG, 'pg_isready', '-U', 'postgres', '-h', '127.0.0.1').status === 0);

  const env = {
    ...process.env,
    NELCOTA_DATABASE_URL: `postgres://postgres:postgres@127.0.0.1:${PG_PORT}/postgres`,
    NELCOTA_AUTHENTICATOR_PASSWORD: 'sdk-contract-authenticator',
    NELCOTA_JWT_SECRET: JWT_SECRET,
    NELCOTA_LISTEN: `127.0.0.1:${API_PORT}`,
    NELCOTA_AUTH_RATE_LIMIT_PER_MINUTE: '100000',
    NELCOTA_STORAGE_BACKEND: 'disk',
    NELCOTA_STORAGE_DIR: storageDir,
    NELCOTA_STORAGE_MIN_FREE_BYTES: '0',
    NELCOTA_SMTP_URL: `smtp://127.0.0.1:${SMTP_PORT}`,
    NELCOTA_SMTP_FROM: 'Nelcota SDK <no-reply@example.com>',
    NELCOTA_PASSWORD_RECOVERY_URL: 'https://app.example.com/new-password',
    NELCOTA_MAGIC_LINK_URL: 'https://app.example.com/signed-in',
    RUST_LOG: 'warn',
  };
  server = spawn(bin, ['serve'], { env, stdio: ['ignore', 'inherit', 'inherit'] });
  server.on('exit', (code) => {
    if (code !== null && code !== 0) console.error(`nelcota serve exited with ${code}`);
  });
  const url = `http://127.0.0.1:${API_PORT}`;
  await waitFor('nelcota serve', async () => {
    try {
      return (await fetch(`${url}/health`)).ok;
    } catch {
      return false;
    }
  });

  run('docker', ['exec', '-i', PG, 'psql', '-q', '-v', 'ON_ERROR_STOP=1', '-U', 'postgres'], {
    input: readFileSync(join(root, 'test/contract/fixture.sql')),
    stdio: ['pipe', 'inherit', 'inherit'],
  });

  // The types the tests compile against come from the real generator.
  const generated = join(root, 'test/contract/generated');
  mkdirSync(generated, { recursive: true });
  run(bin, ['types', '-o', join(generated, 'database.ts')], { env });
  run(process.execPath, [join(root, 'node_modules/typescript/bin/tsc'), '-p', join(root, 'test/contract/tsconfig.json')]);

  // The catalog reloads on DDL; wait until the fixture tables are served.
  await waitFor('catalog reload', async () => (await fetch(`${url}/rest/v1/customers`)).ok, 15);

  const tests = spawnSync(
    process.execPath,
    [join(root, 'node_modules/vitest/vitest.mjs'), 'run', '--project', 'contract', ...vitestArgs],
    {
      cwd: root,
      stdio: 'inherit',
      env: {
        ...process.env,
        NELCOTA_SDK_TEST_URL: url,
        NELCOTA_SDK_TEST_JWT_SECRET: JWT_SECRET,
        NELCOTA_SDK_TEST_MAIL: `http://127.0.0.1:${MAIL_PORT}`,
      },
    },
  );
  status = tests.status ?? 1;

  if (browser && status === 0) {
    run(process.execPath, [join(root, 'scripts/clean.mjs')]);
    run(process.execPath, [join(root, 'node_modules/typescript/bin/tsc'), '-p', join(root, 'tsconfig.build.json')]);
    const encode = (value) => Buffer.from(JSON.stringify(value)).toString('base64url');
    const now = Math.floor(Date.now() / 1000);
    const body = `${encode({ alg: 'HS256', typ: 'JWT' })}.${encode({ role: 'service_role', iat: now, exp: now + 600 })}`;
    const serviceToken = `${body}.${createHmac('sha256', JWT_SECRET).update(body).digest('base64url')}`;
    const smoke = spawnSync(process.execPath, [join(root, 'test/browser/smoke.mjs'), url, serviceToken], { stdio: 'inherit' });
    status = smoke.status ?? 1;
  }
  if (keep) console.log(`\nKept running: ${url} (containers ${PG}, ${MAIL}; stop the server with Ctrl+C)`);
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
} finally {
  teardown();
}
if (!keep) process.exit(status);
