//! Caddy: one site per project, generated from the registry. On Docker hosts
//! it is a shared container; on systemd hosts, the distribution's service.

use std::{fs, process::Command};

use anyhow::{Context, bail};

use crate::{
    host::{Host, Manifest, Runtime},
    native,
    project::compose_command,
    util::ok,
};

/// Docker network that connects Caddy to the projects' apps.
pub const NETWORK: &str = "nelcota_edge";

const COMPOSE: &str = include_str!("../../../deploy/caddy-compose.yml");

/// Caddyfile with one block per project.
pub fn render(manifest: &Manifest) -> String {
    let mut out = String::from(
        "# Generated by nelcota from nelcota-host.json. Do not edit by hand:\n\
         # use `nelcota init` / `nelcota remove`.\n",
    );
    for project in &manifest.projects {
        let upstream = match manifest.runtime {
            Runtime::Docker => format!("app-{}:8000", project.name),
            Runtime::Systemd => native::APP_LISTEN.to_owned(),
        };
        let tls = if manifest.local {
            "\ttls internal\n"
        } else {
            ""
        };
        out.push_str(&format!(
            "\n{domain} {{\n{tls}\tencode zstd gzip\n\treverse_proxy {upstream}\n\theader {{\n\
             \t\t-Server\n\t\tStrict-Transport-Security \"max-age=31536000\"\n\
             \t\tX-Content-Type-Options \"nosniff\"\n\t}}\n}}\n",
            domain = project.domain,
        ));
    }
    out
}

/// Writes the Caddyfile (and, on Docker, Caddy's compose if it does not exist yet).
pub fn write(host: &Host, manifest: &Manifest) -> anyhow::Result<()> {
    if manifest.runtime == Runtime::Systemd {
        return native::write_caddyfile(&render(manifest));
    }
    let dir = host.caddy_dir();
    fs::create_dir_all(dir.join("config"))?;
    let compose = dir.join("docker-compose.yml");
    if !compose.is_file() {
        fs::write(&compose, COMPOSE)?;
    }
    // Atomic swap inside the mounted folder (a single-file bind would not see the rename).
    let tmp = dir.join("config").join("Caddyfile.tmp");
    fs::write(&tmp, render(manifest))?;
    fs::rename(&tmp, dir.join("config").join("Caddyfile"))?;
    Ok(())
}

pub fn ensure_network() -> anyhow::Result<()> {
    let exists = Command::new("docker")
        .args(["network", "inspect", NETWORK])
        .output()
        .context("Docker not found")?
        .status
        .success();
    if !exists {
        let status = Command::new("docker")
            .args(["network", "create", NETWORK])
            .status()?;
        if !status.success() {
            bail!("could not create the {NETWORK} network");
        }
    }
    Ok(())
}

fn running(host: &Host) -> bool {
    compose_command(&host.caddy_dir())
        .args(["ps", "-q", "caddy"])
        .output()
        .map(|o| !String::from_utf8_lossy(&o.stdout).trim().is_empty())
        .unwrap_or(false)
}

/// Starts Caddy (or reloads the configuration if it is already up).
pub fn up(host: &Host, runtime: Runtime) -> anyhow::Result<()> {
    if runtime == Runtime::Systemd {
        native::systemctl(&["enable".into(), "--now".into(), "caddy".into()])?;
        return reload(host, runtime);
    }
    if running(host) {
        return reload(host, runtime);
    }
    let status = compose_command(&host.caddy_dir())
        .args(["up", "-d"])
        .status()?;
    if !status.success() {
        bail!("could not start Caddy");
    }
    ok("caddy up");
    Ok(())
}

/// Applies the new Caddyfile without dropping connections (if Caddy is up).
pub fn reload(host: &Host, runtime: Runtime) -> anyhow::Result<()> {
    if runtime == Runtime::Systemd {
        if native::unit_state("caddy").as_deref() == Some("active") {
            native::systemctl(&["reload".into(), "caddy".into()])?;
            ok("caddy reloaded");
        }
        return Ok(());
    }
    if !running(host) {
        return Ok(());
    }
    let status = compose_command(&host.caddy_dir())
        .args([
            "exec",
            "-T",
            "caddy",
            "caddy",
            "reload",
            "--config",
            "/etc/caddy/Caddyfile",
            "--adapter",
            "caddyfile",
        ])
        .status()?;
    if !status.success() {
        bail!("Caddy rejected the new configuration (see `docker logs nelcota-edge-caddy-1`)");
    }
    ok("caddy reloaded");
    Ok(())
}

pub fn down(host: &Host, runtime: Runtime, volumes: bool) -> anyhow::Result<()> {
    if runtime == Runtime::Systemd {
        return native::systemctl(&["stop".into(), "caddy".into()]);
    }
    let mut args = vec!["down"];
    if volumes {
        args.push("--volumes");
    }
    compose_command(&host.caddy_dir()).args(&args).status()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host::{PanelLogin, ProjectEntry};

    fn manifest(local: bool) -> Manifest {
        Manifest {
            version: 1,
            panel_login: PanelLogin::Shared,
            base_domain: None,
            local,
            runtime: crate::host::Runtime::Docker,
            image: "nelcota".into(),
            projects: vec![
                ProjectEntry {
                    name: "shop".into(),
                    domain: "api.shop.com".into(),
                },
                ProjectEntry {
                    name: "blog".into(),
                    domain: "blog.example.com".into(),
                },
            ],
        }
    }

    #[test]
    fn one_site_per_project() {
        let caddyfile = render(&manifest(false));
        assert!(
            caddyfile.contains("api.shop.com {\n\tencode zstd gzip\n\treverse_proxy app-shop:8000")
        );
        assert!(caddyfile.contains("blog.example.com {"));
        assert!(caddyfile.contains("reverse_proxy app-blog:8000"));
        assert!(!caddyfile.contains("tls internal"));
        assert!(render(&manifest(true)).contains("api.shop.com {\n\ttls internal\n"));
    }
}
