//! Machine setup when the host is created (Linux, as root): a backup cron for
//! every project, the firewall and automatic updates.

use std::{fs, process::Command};

use crate::{
    host::Host,
    util::{ok, step, warn},
};

fn is_root() -> bool {
    Command::new("id")
        .arg("-u")
        .output()
        .is_ok_and(|o| String::from_utf8_lossy(&o.stdout).trim() == "0")
}

pub fn setup(host: &Host, firewall: bool) {
    if !cfg!(target_os = "linux") || !is_root() {
        warn("run as root on a Linux VPS to install the backup cron and the firewall");
        return;
    }
    step("Configuring the machine");
    install_backup_cron(host);
    configure_firewall(firewall);
    if !Command::new("dpkg")
        .args(["-s", "unattended-upgrades"])
        .output()
        .is_ok_and(|o| o.status.success())
    {
        warn("recommended: apt install unattended-upgrades (automatic security updates)");
    }
}

/// Where `init` installs the daily backup job.
pub const BACKUP_CRON: &str = "/etc/cron.d/nelcota-backup";

fn install_backup_cron(host: &Host) {
    let root = fs::canonicalize(host.root()).unwrap_or_else(|_| host.root().to_path_buf());
    let exe = std::env::current_exe()
        .map(|p| p.display().to_string())
        .unwrap_or_else(|_| "/usr/local/bin/nelcota".into());
    match fs::write(BACKUP_CRON, cron_file(&exe, &root.display().to_string())) {
        Ok(()) => ok(&format!("daily backup at 03:00 ({BACKUP_CRON})")),
        Err(e) => warn(&format!("could not install the backup cron: {e}")),
    }
}

/// `backup` uploads on its own when `host.env` has a bucket, so the job keeps
/// working when S3 is configured after `init`.
fn cron_file(exe: &str, root: &str) -> String {
    format!(
        "# Daily backup of every nelcota project (generated by `nelcota init`)\n\
         0 3 * * * root {} -C {} backup --all --keep 7 >> /var/log/nelcota-backup.log 2>&1\n",
        cron_quote(exe),
        cron_quote(root)
    )
}

/// Single-quoted for `sh`, with `%` escaped (cron turns it into a newline).
fn cron_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''").replace('%', r"\%"))
}

fn configure_firewall(enable: bool) {
    let has_ufw = Command::new("ufw").arg("--version").output().is_ok();
    if !has_ufw {
        return;
    }
    if !enable {
        warn(
            "recommended: nelcota init --firewall (or: ufw allow OpenSSH && ufw allow 80/tcp && ufw allow 443 && ufw enable)",
        );
        return;
    }
    let rules: [&[&str]; 4] = [
        &["allow", "OpenSSH"],
        &["allow", "80/tcp"],
        &["allow", "443"],
        &["--force", "enable"],
    ];
    let all_ok = rules.iter().all(|rule| {
        Command::new("ufw")
            .args(*rule)
            .output()
            .is_ok_and(|o| o.status.success())
    });
    if all_ok {
        ok("ufw: SSH, 80 and 443 allowed; everything else blocked");
    } else {
        warn("could not configure ufw; check with `ufw status`");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cron_quotes_paths_and_lets_backup_decide_the_upload() {
        let cron = cron_file("/usr/local/bin/nelcota", "/srv/my hosts/it's 100%");
        assert!(cron.contains(
            r"root '/usr/local/bin/nelcota' -C '/srv/my hosts/it'\''s 100\%' backup --all --keep 7 >>"
        ));
        assert!(!cron.contains("--upload"));
        assert!(cron.ends_with("2>&1\n"));
    }
}
