//! Machine setup when the host is created (Linux, as root): a backup cron for
//! every project, the firewall and automatic updates.

use std::{fs, process::Command};

use crate::{
    host::Host,
    util::{ok, step, warn},
};

fn is_root() -> bool {
    Command::new("id")
        .arg("-u")
        .output()
        .is_ok_and(|o| String::from_utf8_lossy(&o.stdout).trim() == "0")
}

pub fn setup(host: &Host, has_s3: bool, firewall: bool) {
    if !cfg!(target_os = "linux") || !is_root() {
        warn("run as root on a Linux VPS to install the backup cron and the firewall");
        return;
    }
    step("Configuring the machine");
    install_backup_cron(host, has_s3);
    configure_firewall(firewall);
    if !Command::new("dpkg")
        .args(["-s", "unattended-upgrades"])
        .output()
        .is_ok_and(|o| o.status.success())
    {
        warn("recommended: apt install unattended-upgrades (automatic security updates)");
    }
}

fn install_backup_cron(host: &Host, has_s3: bool) {
    let root = fs::canonicalize(host.root()).unwrap_or_else(|_| host.root().to_path_buf());
    let exe = std::env::current_exe()
        .map(|p| p.display().to_string())
        .unwrap_or_else(|_| "/usr/local/bin/nelcota".into());
    let upload = if has_s3 { " --upload" } else { "" };
    let cron = format!(
        "# Daily backup of every nelcota project (generated by `nelcota init`)\n\
         0 3 * * * root {exe} -C {} backup --all{upload} --keep 7 >> /var/log/nelcota-backup.log 2>&1\n",
        root.display()
    );
    match fs::write("/etc/cron.d/nelcota-backup", cron) {
        Ok(()) => ok("daily backup at 03:00 (/etc/cron.d/nelcota-backup)"),
        Err(e) => warn(&format!("could not install the backup cron: {e}")),
    }
}

fn configure_firewall(enable: bool) {
    let has_ufw = Command::new("ufw").arg("--version").output().is_ok();
    if !has_ufw {
        return;
    }
    if !enable {
        warn(
            "recommended: nelcota init --firewall (or: ufw allow OpenSSH && ufw allow 80/tcp && ufw allow 443 && ufw enable)",
        );
        return;
    }
    let rules: [&[&str]; 4] = [
        &["allow", "OpenSSH"],
        &["allow", "80/tcp"],
        &["allow", "443"],
        &["--force", "enable"],
    ];
    let all_ok = rules.iter().all(|rule| {
        Command::new("ufw")
            .args(*rule)
            .output()
            .is_ok_and(|o| o.status.success())
    });
    if all_ok {
        ok("ufw: SSH, 80 and 443 allowed; everything else blocked");
    } else {
        warn("could not configure ufw; check with `ufw status`");
    }
}
