//! Hosts without Docker (`nelcota init --runtime systemd`): one project per
//! machine, on Debian or Ubuntu. Postgres 17 and pgBackRest come from the
//! PostgreSQL project's apt repository (PGDG), Caddy from its own, and the
//! app is a hardened systemd unit running a copy of this binary.
//!
//! ```text
//! /usr/local/lib/nelcota/nelcota            the binary the unit runs (nelcota.previous: rollback)
//! /etc/systemd/system/nelcota-<name>.service
//! /etc/postgresql/17/main/conf.d/nelcota.conf   the Postgres profile
//! /etc/caddy/Caddyfile                      generated from nelcota-host.json
//! /etc/pgbackrest/pgbackrest.conf           with PITR on
//! ```

use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use anyhow::{Context, bail};

use crate::{
    project::{Project, run},
    scaffold,
    util::{ok, step},
};

pub const POSTGRES_UNIT: &str = "postgresql@17-main";
pub const PG_DATA: &str = "/var/lib/postgresql/17/main";
const PG_CONF: &str = "/etc/postgresql/17/main/conf.d/nelcota.conf";
/// The app answers only on loopback; Caddy is the way in.
pub const APP_LISTEN: &str = "127.0.0.1:8000";
pub const CADDYFILE: &str = "/etc/caddy/Caddyfile";
pub const PGBACKREST_CONF: &str = "/etc/pgbackrest/pgbackrest.conf";
const LIB_DIR: &str = "/usr/local/lib/nelcota";

pub fn app_unit(project: &str) -> String {
    format!("nelcota-{project}")
}

// Paths on the Linux machine, spelled with `/` whatever compiles the CLI.

pub fn unit_path(project: &str) -> PathBuf {
    PathBuf::from(format!("/etc/systemd/system/{}.service", app_unit(project)))
}

/// The binary the unit runs, and the one kept for a rollback.
pub fn deployed_binary() -> PathBuf {
    PathBuf::from(format!("{LIB_DIR}/nelcota"))
}

fn previous_binary() -> PathBuf {
    PathBuf::from(format!("{LIB_DIR}/nelcota.previous"))
}

pub fn systemctl(args: &[String]) -> anyhow::Result<()> {
    run(
        Command::new("systemctl").args(args),
        &format!("systemctl {}", args.join(" ")),
    )
}

pub fn systemctl_quiet(args: &[String]) -> anyhow::Result<()> {
    let status = Command::new("systemctl")
        .args(args)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()?;
    if !status.success() {
        bail!("systemctl {} failed", args.join(" "));
    }
    Ok(())
}

/// `active`, `inactive`, `failed`, `activating`...; `None` without systemd.
pub fn unit_state(unit: &str) -> Option<String> {
    let output = Command::new("systemctl")
        .args(["is-active", unit])
        .output()
        .ok()?;
    let state = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    (!state.is_empty()).then_some(state)
}

/// The app's unit: this binary as `serve`, the project's `.env`, a
/// throwaway system user and no write access anywhere.
pub fn render_unit(project: &str, env_file: &Path) -> String {
    format!(
        "# nelcota project \"{project}\". Generated by `nelcota init`.\n\
         [Unit]\n\
         Description=nelcota ({project})\n\
         After=network-online.target {POSTGRES_UNIT}.service\n\
         Wants=network-online.target\n\
         Requires={POSTGRES_UNIT}.service\n\
         \n\
         [Service]\n\
         ExecStart={binary} serve\n\
         EnvironmentFile={env}\n\
         Environment=NELCOTA_LISTEN={APP_LISTEN}\n\
         Environment=NELCOTA_TRUST_PROXY=true\n\
         Environment=NELCOTA_PROJECT_NAME={project}\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         DynamicUser=yes\n\
         StateDirectory=nelcota-{project}\n\
         CapabilityBoundingSet=\n\
         NoNewPrivileges=yes\n\
         ProtectSystem=strict\n\
         ProtectHome=yes\n\
         PrivateTmp=yes\n\
         PrivateDevices=yes\n\
         ProtectKernelTunables=yes\n\
         ProtectKernelModules=yes\n\
         ProtectControlGroups=yes\n\
         RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX\n\
         LockPersonality=yes\n\
         MemoryDenyWriteExecute=yes\n\
         SystemCallArchitectures=native\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n",
        binary = deployed_binary().display(),
        env = env_file.display(),
    )
}

/// The Postgres profile as a `conf.d` file (the Debian packaging includes it).
pub fn render_postgres_conf(profile: &str) -> String {
    format!(
        "# Postgres profile {profile} for nelcota (generated by `nelcota init`).\n{}",
        scaffold::profile_settings(profile)
            .iter()
            .map(|(k, v)| format!("{k} = '{v}'\n"))
            .collect::<String>()
    )
}

/// Linux, root, and apt on Debian or Ubuntu.
pub fn check_machine() -> anyhow::Result<()> {
    if !cfg!(target_os = "linux") {
        bail!("--runtime systemd needs a Linux machine (Debian or Ubuntu)");
    }
    let root = Command::new("id")
        .arg("-u")
        .output()
        .is_ok_and(|o| String::from_utf8_lossy(&o.stdout).trim() == "0");
    if !root {
        bail!("--runtime systemd installs packages and services: run it as root");
    }
    let release = fs::read_to_string("/etc/os-release").unwrap_or_default();
    let supported = release.lines().any(|l| {
        matches!(
            l,
            "ID=debian" | "ID=ubuntu" | "ID_LIKE=debian" | "ID_LIKE=\"ubuntu debian\""
        )
    });
    if !supported || Command::new("apt-get").arg("--version").output().is_err() {
        bail!("--runtime systemd supports Debian and Ubuntu (apt); use Docker elsewhere");
    }
    if unit_state("systemd-journald").is_none() {
        bail!("systemd is not running on this machine");
    }
    ok("Debian/Ubuntu with systemd, as root");
    Ok(())
}

/// Postgres 17 + pgBackRest (PGDG) and Caddy (its apt repository).
pub fn install_packages() -> anyhow::Result<()> {
    step("Installing Postgres 17, pgBackRest and Caddy (apt)");
    let script = r#"set -e
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -y -q curl ca-certificates gnupg postgresql-common
if ! ls /etc/apt/sources.list.d/ | grep -q pgdg; then
  /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
fi
if [ ! -f /usr/share/keyrings/caddy-stable-archive-keyring.gpg ]; then
  curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
    > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -q
fi
apt-get install -y -q postgresql-17 pgbackrest caddy
"#;
    run(
        Command::new("sh").args(["-c", script]),
        "the package installation",
    )?;
    ok("packages installed");
    Ok(())
}

/// The 17/main cluster with the profile and the `postgres` password the
/// app's `NELCOTA_DATABASE_URL` uses (over 127.0.0.1, scram-sha-256).
pub fn configure_postgres(profile: &str, password: &str) -> anyhow::Result<()> {
    step("Configuring Postgres 17");
    let clusters = Command::new("pg_lsclusters")
        .arg("--no-header")
        .output()
        .context("pg_lsclusters not found (is postgresql-17 installed?)")?;
    let exists = String::from_utf8_lossy(&clusters.stdout)
        .lines()
        .any(|l| l.split_whitespace().take(2).eq(["17", "main"]));
    if !exists {
        run(
            Command::new("pg_createcluster").args(["17", "main"]),
            "pg_createcluster",
        )?;
    }
    fs::write(PG_CONF, render_postgres_conf(profile))?;
    systemctl(&["enable".into(), POSTGRES_UNIT.into()])?;
    systemctl(&["restart".into(), POSTGRES_UNIT.into()])?;
    // Alphanumeric (util::secret): safe inside the literal.
    run(
        Command::new("runuser").args([
            "-u",
            "postgres",
            "--",
            "psql",
            "-q",
            "-c",
            &format!("ALTER ROLE postgres PASSWORD '{password}'"),
        ]),
        "setting the postgres password",
    )?;
    ok(&format!("cluster 17/main with the {profile} profile"));
    Ok(())
}

/// Copies this binary to where the unit runs it. The one there before is
/// kept as `nelcota.previous`.
pub fn deploy_binary() -> anyhow::Result<()> {
    fs::create_dir_all(LIB_DIR)?;
    let target = deployed_binary();
    if target.is_file() {
        fs::copy(&target, previous_binary())?;
    }
    // Copy then rename: the running binary cannot be overwritten in place.
    let tmp = target.with_extension("new");
    fs::copy(std::env::current_exe()?, &tmp)?;
    fs::rename(&tmp, &target)?;
    Ok(())
}

/// Puts back the binary from before the last [`deploy_binary`].
pub fn rollback_binary() -> anyhow::Result<()> {
    let previous = previous_binary();
    if !previous.is_file() {
        bail!("no previous binary at {}", previous.display());
    }
    fs::rename(previous, deployed_binary())?;
    Ok(())
}

/// The app's unit file and systemd's view of it.
pub fn install_unit(project: &Project) -> anyhow::Result<()> {
    fs::write(
        unit_path(&project.name),
        render_unit(&project.name, &project.path(".env")),
    )?;
    systemctl(&["daemon-reload".into()])?;
    ok(&format!("unit {}.service", app_unit(&project.name)));
    Ok(())
}

/// Removes the app's unit and the Postgres cluster with its data.
pub fn remove(project: &Project) -> anyhow::Result<()> {
    let unit = app_unit(&project.name);
    let _ = systemctl_quiet(&["disable".into(), "--now".into(), unit]);
    let _ = fs::remove_file(unit_path(&project.name));
    systemctl(&["daemon-reload".into()])?;
    run(
        Command::new("pg_dropcluster").args(["17", "main", "--stop"]),
        "pg_dropcluster",
    )?;
    let _ = fs::remove_file(PGBACKREST_CONF);
    Ok(())
}

/// Writes the Caddyfile atomically.
pub fn write_caddyfile(content: &str) -> anyhow::Result<()> {
    let path = Path::new(CADDYFILE);
    let tmp = path.with_extension("nelcota-tmp");
    fs::write(&tmp, content)?;
    fs::rename(&tmp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_unit_runs_the_deployed_binary_locked_down() {
        let unit = render_unit("shop", Path::new("/opt/nelcota/projects/shop/.env"));
        for line in [
            "ExecStart=/usr/local/lib/nelcota/nelcota serve",
            "EnvironmentFile=/opt/nelcota/projects/shop/.env",
            "Environment=NELCOTA_LISTEN=127.0.0.1:8000",
            "Environment=NELCOTA_PROJECT_NAME=shop",
            "Requires=postgresql@17-main.service",
            "DynamicUser=yes",
            "StateDirectory=nelcota-shop",
            "ProtectSystem=strict",
            "WantedBy=multi-user.target",
        ] {
            assert!(unit.lines().any(|l| l == line), "{line} missing:\n{unit}");
        }
    }

    #[test]
    fn the_profile_becomes_a_conf_d_file() {
        let conf = render_postgres_conf("1gb");
        assert!(conf.contains("shared_buffers = '128MB'\n"), "{conf}");
        assert!(conf.contains("shared_preload_libraries = 'pg_stat_statements'\n"));
        let comments = conf.lines().filter(|l| l.starts_with('#')).count();
        assert_eq!(comments, 1, "only the header is a comment:\n{conf}");
    }
}
