//! Point-in-time recovery with pgBackRest: Postgres archives every WAL segment
//! to the host's S3-compatible storage, next to periodic base backups, so a
//! project can be restored to any second covered by the archive (not only to
//! the last nightly dump).
//!
//! pgBackRest runs next to Postgres as the postgres user. On Docker hosts it
//! lives in the project's Postgres image (`postgres/Dockerfile` adds it to
//! postgres:17-alpine) and reads its settings as `PGBACKREST_*` variables
//! from `pgbackrest.env`; on systemd hosts it comes from the PGDG packages and
//! reads the same settings from `/etc/pgbackrest/pgbackrest.conf`. Either way
//! `pgbackrest.env` (mode 600, it holds the S3 keys) existing is what "PITR
//! enabled" means for a project.

use std::{
    fs,
    process::Command,
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, bail};

use crate::{
    envfile::{EnvFile, write_private},
    host::{Host, Runtime},
    native,
    project::{Project, Service, run},
    util::{self, ok, step, warn},
};

/// pgBackRest settings of the project (S3 keys included).
pub const ENV_FILE: &str = "pgbackrest.env";
pub const DOCKERFILE: &str = include_str!("../../../deploy/postgres/Dockerfile");
/// How a compose file from before PITR becomes the current template, as
/// `(old, new)` text that must each appear exactly once: Postgres is built
/// from `postgres/Dockerfile`, reads `pgbackrest.env` when PITR is on, and
/// joins an `egress` network of its own to reach S3 (the `internal` network
/// has no way out; nothing can connect in through either).
pub const COMPOSE_UPGRADE: [(&str, &str); 3] = [
    (
        "    image: postgres:17-alpine\n",
        "    # postgres:17-alpine plus pgBackRest (point-in-time recovery: `nelcota pitr`).\n    build: ./postgres\n    env_file:\n      - path: pgbackrest.env\n        required: false\n",
    ),
    (
        "    networks: [internal]\n",
        "    # egress: outbound only, for archiving WAL to S3.\n    networks: [internal, egress]\n",
    ),
    (
        "networks:\n  internal:\n    internal: true\n",
        "networks:\n  internal:\n    internal: true\n  egress: {}\n",
    ),
];
const STANZA: &str = "--stanza=main";
const ARCHIVE_COMMAND: &str = "pgbackrest --stanza=main archive-push %p";
/// Full base backups kept; older ones (and the WAL only they need) expire.
const RETENTION_FULL: u32 = 2;
const RECOVERY_TIMEOUT: Duration = Duration::from_secs(3600);
const HEALTH_TIMEOUT: Duration = Duration::from_secs(120);

pub fn enabled(project: &Project) -> bool {
    project.path(ENV_FILE).is_file()
}

/// Writes `postgres/Dockerfile` into a project folder.
pub fn write_dockerfile(project: &Project) -> anyhow::Result<()> {
    let dir = project.path("postgres");
    fs::create_dir_all(&dir)?;
    fs::write(dir.join("Dockerfile"), DOCKERFILE)?;
    Ok(())
}

/// `pgbackrest.env` for a project, from the host's S3 settings. The
/// repository is `<bucket>/<project>/pitr`, beside the dumps' `<project>/`.
fn render_env(project: &str, pg_data: &str, host: &EnvFile) -> anyhow::Result<String> {
    let get = |key: &str| -> anyhow::Result<String> {
        host.get(key)?.with_context(|| {
            format!("{key} is not set in host.env: PITR needs S3-compatible storage (see docs/backup.md)")
        })
    };
    let endpoint = get("NELCOTA_BACKUP_S3_ENDPOINT")?;
    let (endpoint_host, port) = split_endpoint(&endpoint)?;
    let region = host
        .get("NELCOTA_BACKUP_S3_REGION")?
        .unwrap_or_else(|| "us-east-1".into());
    let uri_style = host
        .get("NELCOTA_BACKUP_S3_URI_STYLE")?
        .unwrap_or_else(|| "host".into());
    if !matches!(uri_style.as_str(), "host" | "path") {
        bail!("NELCOTA_BACKUP_S3_URI_STYLE must be host or path, not '{uri_style}'");
    }
    let mut env = format!(
        "# pgBackRest for project \"{project}\". Generated by `nelcota pitr enable` at {now}.\n\
         # CONTAINS SECRETS (S3 keys): mode 600. Regenerate after changing host.env.\n\
         PGBACKREST_REPO1_TYPE=s3\n\
         PGBACKREST_REPO1_PATH=/{project}/pitr\n\
         PGBACKREST_REPO1_S3_ENDPOINT={endpoint_host}\n\
         PGBACKREST_REPO1_S3_BUCKET={bucket}\n\
         PGBACKREST_REPO1_S3_REGION={region}\n\
         PGBACKREST_REPO1_S3_URI_STYLE={uri_style}\n\
         PGBACKREST_REPO1_S3_KEY={key}\n\
         PGBACKREST_REPO1_S3_KEY_SECRET={secret}\n\
         PGBACKREST_REPO1_RETENTION_FULL={RETENTION_FULL}\n\
         PGBACKREST_PG1_PATH={pg_data}\n\
         PGBACKREST_START_FAST=y\n\
         PGBACKREST_LOG_LEVEL_CONSOLE=warn\n\
         PGBACKREST_LOG_LEVEL_FILE=off\n",
        now = util::timestamp(),
        bucket = get("NELCOTA_BACKUP_S3_BUCKET")?,
        key = get("NELCOTA_BACKUP_S3_ACCESS_KEY")?,
        secret = get("NELCOTA_BACKUP_S3_SECRET_KEY")?,
    );
    if let Some(port) = port {
        env.push_str(&format!("PGBACKREST_REPO1_STORAGE_PORT={port}\n"));
    }
    // Only for storage with a self-signed certificate (a MinIO of your own).
    if host.get("NELCOTA_BACKUP_S3_VERIFY_TLS")?.as_deref() == Some("false") {
        env.push_str("PGBACKREST_REPO1_STORAGE_VERIFY_TLS=n\n");
    }
    Ok(env)
}

/// The same settings as a `pgbackrest.conf`: `PGBACKREST_REPO1_S3_KEY=x`
/// becomes `repo1-s3-key=x`, the Postgres path goes to the stanza.
fn render_conf(env: &str) -> String {
    let mut global = String::from("[global]\n");
    let mut stanza = String::from("\n[main]\n");
    for line in env.lines() {
        let Some((key, value)) = line
            .strip_prefix("PGBACKREST_")
            .and_then(|l| l.split_once('='))
        else {
            continue;
        };
        let option = key.to_lowercase().replace('_', "-");
        let section = if option.starts_with("pg1-") {
            &mut stanza
        } else {
            &mut global
        };
        section.push_str(&format!("{option}={value}\n"));
    }
    format!(
        "# Generated by `nelcota pitr enable` from pgbackrest.env. CONTAINS SECRETS.\n{global}{stanza}"
    )
}

/// `https://s3.example.com:9000/` → (`s3.example.com`, Some(9000)).
/// pgBackRest always speaks HTTPS to S3.
fn split_endpoint(endpoint: &str) -> anyhow::Result<(String, Option<u16>)> {
    if endpoint.starts_with("http://") {
        bail!("pgBackRest only talks to S3 over HTTPS: NELCOTA_BACKUP_S3_ENDPOINT is {endpoint}");
    }
    let rest = endpoint.strip_prefix("https://").unwrap_or(endpoint);
    let authority = rest.split('/').next().unwrap_or_default();
    match authority.rsplit_once(':') {
        Some((host, port)) => {
            let port = port.parse().with_context(|| {
                format!("invalid port in NELCOTA_BACKUP_S3_ENDPOINT: {endpoint}")
            })?;
            Ok((host.to_owned(), Some(port)))
        }
        None if !authority.is_empty() => Ok((authority.to_owned(), None)),
        None => bail!("invalid NELCOTA_BACKUP_S3_ENDPOINT: {endpoint}"),
    }
}

/// Brings a compose file from before PITR to the current template (see
/// [`COMPOSE_UPGRADE`]). `false` when it was edited beyond recognition.
fn upgrade_compose(project: &Project) -> anyhow::Result<bool> {
    let path = project.path("docker-compose.yml");
    let mut compose = fs::read_to_string(&path)?;
    if COMPOSE_UPGRADE.iter().all(|(_, new)| compose.contains(new)) {
        return Ok(true);
    }
    if COMPOSE_UPGRADE
        .iter()
        .any(|(old, _)| compose.matches(old).count() != 1)
    {
        return Ok(false);
    }
    for (old, new) in COMPOSE_UPGRADE {
        compose = compose.replace(old, new);
    }
    fs::write(&path, compose)?;
    ok("docker-compose.yml: Postgres built with pgBackRest, with an egress network");
    Ok(true)
}

/// Turns WAL archiving on and takes the first full backup.
pub fn enable(host: &Host, project: &Project) -> anyhow::Result<()> {
    let pg_data = match project.runtime {
        Runtime::Docker => "/var/lib/postgresql/data",
        Runtime::Systemd => native::PG_DATA,
    };
    let env = render_env(&project.name, pg_data, &host.secrets())?;
    step(&format!(
        "Enabling point-in-time recovery for {}",
        project.name
    ));
    match project.runtime {
        Runtime::Docker => {
            write_dockerfile(project)?;
            if !upgrade_compose(project)? {
                let changes: Vec<String> = COMPOSE_UPGRADE
                    .iter()
                    .map(|(old, new)| format!("replace:\n{old}with:\n{new}"))
                    .collect();
                bail!(
                    "{} was edited and could not be updated; make these changes and run this again:\n\n{}",
                    project.path("docker-compose.yml").display(),
                    changes.join("\n")
                );
            }
            write_private(&project.path(ENV_FILE), &env)?;
            step("Rebuilding Postgres with pgBackRest");
            project.compose_ok(&["up", "-d", "--build", "postgres"])?;
        }
        Runtime::Systemd => {
            write_private(&project.path(ENV_FILE), &env)?;
            fs::create_dir_all("/etc/pgbackrest")?;
            write_private(native::PGBACKREST_CONF.as_ref(), &render_conf(&env))?;
            run(
                Command::new("chown").args(["postgres:postgres", native::PGBACKREST_CONF]),
                "chown of pgbackrest.conf",
            )?;
        }
    }
    project.wait_healthy(Service::Postgres, HEALTH_TIMEOUT)?;
    pgbackrest(project, &["stanza-create"]).context("could not create the repository in S3")?;

    step("Archiving WAL");
    psql(
        project,
        &[
            "ALTER SYSTEM SET archive_mode = on",
            &format!("ALTER SYSTEM SET archive_command = '{ARCHIVE_COMMAND}'"),
            // An idle database still ships its last writes within a minute.
            "ALTER SYSTEM SET archive_timeout = '60s'",
        ],
    )?;
    project.recreate(Service::Postgres)?;
    project.wait_healthy(Service::Postgres, HEALTH_TIMEOUT)?;
    pgbackrest(project, &["check"]).context("WAL archiving check failed")?;

    step("First full backup");
    pgbackrest(project, &["--type=full", "backup"])?;
    ok(&format!(
        "PITR on: restore any moment from now with `nelcota -p {} pitr restore --time ...`",
        project.name
    ));
    Ok(())
}

/// Stops archiving. The backups already in S3 stay there.
pub fn disable(project: &Project) -> anyhow::Result<()> {
    if !enabled(project) {
        bail!("PITR is not enabled for {}", project.name);
    }
    step(&format!(
        "Disabling point-in-time recovery for {}",
        project.name
    ));
    psql(
        project,
        &[
            "ALTER SYSTEM RESET archive_command",
            "ALTER SYSTEM RESET archive_mode",
            "ALTER SYSTEM RESET archive_timeout",
        ],
    )?;
    fs::remove_file(project.path(ENV_FILE))?;
    if project.runtime == Runtime::Systemd {
        let _ = fs::remove_file(native::PGBACKREST_CONF);
    }
    project.recreate(Service::Postgres)?;
    project.wait_healthy(Service::Postgres, HEALTH_TIMEOUT)?;
    ok("archiving stopped; the backups already in S3 were kept");
    Ok(())
}

/// Backups and the WAL range the archive covers (`pgbackrest info`).
pub fn status(project: &Project) -> anyhow::Result<()> {
    if !enabled(project) {
        println!(
            "PITR is off for {}: nelcota -p {} pitr enable",
            project.name, project.name
        );
        return Ok(());
    }
    pgbackrest(project, &["info"])
}

/// A base backup: full on Sundays, differential (changes since the last
/// full) on the other days. Shorter WAL replays on restore.
pub fn backup(project: &Project) -> anyhow::Result<()> {
    let kind = if weekday_utc() == 0 { "full" } else { "diff" };
    step(&format!("PITR base backup of {} ({kind})", project.name));
    pgbackrest(project, &[&format!("--type={kind}"), "backup"])?;
    ok("base backup stored in S3");
    Ok(())
}

/// 0 = Sunday.
fn weekday_utc() -> u64 {
    let days = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |d| d.as_secs() / 86_400);
    // 1970-01-01 was a Thursday.
    (days + 4) % 7
}

/// Restores the database to `time` (or to the last archived write) and
/// starts a new timeline from there.
pub fn restore(project: &Project, time: Option<&str>, yes: bool) -> anyhow::Result<()> {
    if !enabled(project) {
        bail!("PITR is not enabled for {}", project.name);
    }
    let moment = time.unwrap_or("the last archived write");
    if !yes
        && !(util::interactive()
            && util::confirm(&format!(
                "This REPLACES the {} database with its state at {moment}. \
                 Writes after that are discarded. Continue?",
                project.name
            )))
    {
        bail!("restore cancelled (use --yes to skip the question)");
    }

    step(&format!("Stopping {}", project.name));
    project.stop(&[Service::App, Service::Postgres])?;

    step(&format!("Restoring {} to {moment}", project.name));
    // --delta only rewrites the files that differ from the backup.
    let mut args = vec!["pgbackrest", STANZA, "--delta"];
    let target = time.map(|t| format!("--target={t}"));
    if let Some(target) = &target {
        // Without promote, Postgres would pause at the target, still read-only.
        args.extend(["--type=time", target.as_str(), "--target-action=promote"]);
    }
    args.push("restore");
    if let Err(err) = run(
        &mut project.as_postgres_offline(&args),
        "pgbackrest restore",
    ) {
        // pgBackRest refuses most problems (no backup for that moment, S3
        // unreachable) before touching the data: bring the project back.
        step("Restore refused; starting the project again");
        let _ = project.start(&[Service::Postgres, Service::App]);
        return Err(err.context(
            "the restore did not run; if Postgres does not start, run the restore again",
        ));
    }

    step("Replaying WAL (Postgres starts once it reaches the target)");
    // A fresh start: a crash from now on is this recovery failing.
    project.recreate(Service::Postgres)?;
    wait_for_promotion(project)?;
    ok("database restored");

    // The restore started a new timeline. Backups taken on the old one after
    // the fork cannot serve it, so the next restore needs a backup from here.
    step("New full backup on the restored timeline");
    if let Err(err) = pgbackrest(project, &["--type=full", "backup"]) {
        warn(&format!(
            "{err:#}: take one with `nelcota -p {} pitr backup` before relying on another restore",
            project.name
        ));
    }

    step("Starting the app");
    project.start(&[Service::App])?;
    project.wait_healthy(Service::App, HEALTH_TIMEOUT)?;
    ok(&format!(
        "{} restored to {moment} and healthy",
        project.name
    ));
    Ok(())
}

/// Waits until Postgres has left recovery. A target the archive does not
/// reach makes Postgres exit: that is a failure.
fn wait_for_promotion(project: &Project) -> anyhow::Result<()> {
    let deadline = Instant::now() + RECOVERY_TIMEOUT;
    loop {
        let in_recovery = project
            .as_postgres(&["psql", "-tAc", "SELECT pg_is_in_recovery()"])
            .stderr(std::process::Stdio::null())
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_owned());
        if in_recovery.as_deref() == Some("f") {
            return Ok(());
        }
        if project.postgres_crashed() {
            project.stop(&[Service::Postgres])?;
            bail!(
                "Postgres could not finish the recovery (is the target inside the archive? \
                 see `nelcota -p {0} pitr status` and `nelcota -p {0} logs postgres`); \
                 Postgres was stopped: run the restore again with another --time",
                project.name
            );
        }
        if Instant::now() > deadline {
            bail!(
                "recovery still running after {}s: follow it with `nelcota -p {} logs -f postgres`",
                RECOVERY_TIMEOUT.as_secs(),
                project.name
            );
        }
        std::thread::sleep(Duration::from_secs(2));
    }
}

/// `pgbackrest --stanza=main <args>` as the postgres user.
fn pgbackrest(project: &Project, args: &[&str]) -> anyhow::Result<()> {
    let mut full = vec!["pgbackrest", STANZA];
    full.extend_from_slice(args);
    run(
        &mut project.as_postgres(&full),
        &format!("pgbackrest {}", args.join(" ")),
    )
}

/// Statements outside a transaction (ALTER SYSTEM cannot run in one).
fn psql(project: &Project, statements: &[&str]) -> anyhow::Result<()> {
    let mut args = vec!["psql", "-v", "ON_ERROR_STOP=1", "-q"];
    for statement in statements {
        args.extend(["-c", statement]);
    }
    run(&mut project.as_postgres(&args), "psql")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn host_env(name: &str, content: &str) -> EnvFile {
        let path =
            std::env::temp_dir().join(format!("nelcota-pitr-{name}-{}.env", std::process::id()));
        fs::write(&path, content).unwrap();
        EnvFile::new(path)
    }

    const S3: &str = "NELCOTA_BACKUP_S3_ENDPOINT=https://minio.internal:9000\n\
                      NELCOTA_BACKUP_S3_BUCKET=backups\n\
                      NELCOTA_BACKUP_S3_ACCESS_KEY=AK\n\
                      NELCOTA_BACKUP_S3_SECRET_KEY=SK\n";

    #[test]
    fn the_env_points_pgbackrest_at_the_projects_folder() {
        let env = render_env("shop", "/var/lib/postgresql/data", &host_env("full", S3)).unwrap();
        for line in [
            "PGBACKREST_REPO1_PATH=/shop/pitr",
            "PGBACKREST_REPO1_S3_ENDPOINT=minio.internal",
            "PGBACKREST_REPO1_STORAGE_PORT=9000",
            "PGBACKREST_REPO1_S3_BUCKET=backups",
            "PGBACKREST_REPO1_S3_REGION=us-east-1",
            "PGBACKREST_REPO1_S3_URI_STYLE=host",
            "PGBACKREST_REPO1_S3_KEY=AK",
            "PGBACKREST_REPO1_S3_KEY_SECRET=SK",
        ] {
            assert!(env.lines().any(|l| l == line), "{line} missing:\n{env}");
        }
        assert!(!env.contains("VERIFY_TLS"));

        let own_minio =
            format!("{S3}NELCOTA_BACKUP_S3_VERIFY_TLS=false\nNELCOTA_BACKUP_S3_URI_STYLE=path\n");
        let env = render_env("shop", "/data", &host_env("minio", &own_minio)).unwrap();
        assert!(env.contains("PGBACKREST_REPO1_STORAGE_VERIFY_TLS=n\n"));
        assert!(env.contains("PGBACKREST_REPO1_S3_URI_STYLE=path\n"));

        assert!(render_env("shop", "/data", &host_env("none", "")).is_err());
        let bad_style = format!("{S3}NELCOTA_BACKUP_S3_URI_STYLE=virtual\n");
        assert!(render_env("shop", "/data", &host_env("style", &bad_style)).is_err());
    }

    #[test]
    fn old_compose_files_upgrade_to_the_template() {
        let current = crate::scaffold::render_compose("shop", "1gb");
        let mut old = current.clone();
        for (before, after) in COMPOSE_UPGRADE {
            assert_eq!(current.matches(after).count(), 1, "{after}");
            old = old.replace(after, before);
        }
        let dir = std::env::temp_dir().join(format!("nelcota-pitr-compose-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let file = dir.join("docker-compose.yml");
        fs::write(&file, &old).unwrap();
        let project = Project::new("shop", &dir, Runtime::Docker);
        assert!(upgrade_compose(&project).unwrap());
        assert_eq!(fs::read_to_string(&file).unwrap(), current);
        // Idempotent; an edited file is left alone.
        assert!(upgrade_compose(&project).unwrap());
        assert_eq!(fs::read_to_string(&file).unwrap(), current);
        fs::write(
            &file,
            "services: {}
",
        )
        .unwrap();
        assert!(!upgrade_compose(&project).unwrap());
    }

    #[test]
    fn the_conf_file_holds_the_same_settings() {
        let env = render_env("shop", native::PG_DATA, &host_env("conf", S3)).unwrap();
        let conf = render_conf(&env);
        let (global, stanza) = conf.split_once("\n[main]\n").unwrap();
        assert!(global.contains("[global]\nrepo1-type=s3\n"), "{conf}");
        assert!(global.contains("\nrepo1-s3-key-secret=SK\n"));
        assert!(global.contains("\nrepo1-storage-port=9000\n"));
        assert!(global.contains("\nstart-fast=y\n"));
        assert_eq!(stanza, "pg1-path=/var/lib/postgresql/17/main\n");
    }

    #[test]
    fn endpoints_split_into_host_and_port() {
        assert_eq!(
            split_endpoint("https://s3.us-west-002.backblazeb2.com").unwrap(),
            ("s3.us-west-002.backblazeb2.com".to_owned(), None)
        );
        assert_eq!(
            split_endpoint("https://minio.internal:9000/").unwrap(),
            ("minio.internal".to_owned(), Some(9000))
        );
        assert!(split_endpoint("http://minio:9000").is_err());
        assert!(split_endpoint("https://").is_err());
        assert!(split_endpoint("https://x:port").is_err());
    }
}
