//! Files of a new project: `.env` (the project's secrets), `migrations/`,
//! `backups/` and, on Docker hosts, `docker-compose.yml` and
//! `postgres/Dockerfile`.

use std::fs;

use anyhow::bail;

use crate::{
    envfile::write_private,
    host::{Host, ProjectEntry, Runtime},
    pitr,
    project::Project,
    util,
};

const COMPOSE_TEMPLATE: &str = include_str!("../../../deploy/project-compose.tmpl.yml");
const PROFILES: [(&str, &str); 4] = [
    (
        "1gb",
        include_str!("../../../deploy/postgres/profiles/1gb.conf"),
    ),
    (
        "2gb",
        include_str!("../../../deploy/postgres/profiles/2gb.conf"),
    ),
    (
        "4gb",
        include_str!("../../../deploy/postgres/profiles/4gb.conf"),
    ),
    (
        "8gb",
        include_str!("../../../deploy/postgres/profiles/8gb.conf"),
    ),
];

pub struct NewProject<'a> {
    pub entry: &'a ProjectEntry,
    pub runtime: Runtime,
    pub profile: &'a str,
    pub image: &'a str,
    pub version: &'a str,
}

/// Postgres profile for the RAM available to each project.
pub fn profile_for(ram_mb: u64) -> &'static str {
    match ram_mb {
        0..1536 => "1gb",
        1536..3072 => "2gb",
        3072..6144 => "4gb",
        _ => "8gb",
    }
}

/// The requested profile (validated) or one chosen by the RAM split across the projects.
pub fn choose_profile(
    requested: Option<&str>,
    ram_mb: u64,
    projects: usize,
) -> anyhow::Result<&'static str> {
    match requested {
        Some(p) => PROFILES
            .iter()
            .map(|(name, _)| *name)
            .find(|name| *name == p)
            .ok_or_else(|| anyhow::anyhow!("unknown profile: {p} (use 1gb, 2gb, 4gb or 8gb)")),
        None => Ok(profile_for(ram_mb / projects.max(1) as u64)),
    }
}

/// The `key = value` settings of a `.conf` profile.
pub fn profile_settings(profile: &str) -> Vec<(String, String)> {
    let conf = PROFILES
        .iter()
        .find(|(name, _)| *name == profile)
        .map_or("", |(_, conf)| conf);
    conf.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .filter_map(|l| l.split_once('='))
        .map(|(k, v)| (k.trim().to_owned(), v.trim().to_owned()))
        .collect()
}

/// Turns a `.conf` profile into compose `-c key=value` arguments.
pub fn postgres_args(profile: &str) -> String {
    profile_settings(profile)
        .iter()
        .map(|(k, v)| format!("      - -c\n      - {k}={v}"))
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn render_compose(project: &str, profile: &str) -> String {
    COMPOSE_TEMPLATE
        .replace("{{GENERATED_AT}}", &util::timestamp())
        .replace("{{PROFILE}}", profile)
        .replace("{{POSTGRES_ARGS}}", &postgres_args(profile))
        .replace("{{PROJECT}}", project)
}

fn pool_size(profile: &str) -> u32 {
    match profile {
        "1gb" => 8,
        "2gb" => 15,
        _ => 25,
    }
}

/// Creates the project folder with its own secrets. Fails if it already exists.
pub fn create(host: &Host, new: &NewProject) -> anyhow::Result<()> {
    let dir = host.project_dir(&new.entry.name);
    if dir.join(".env").exists() {
        bail!("a project already exists at {}", dir.display());
    }
    fs::create_dir_all(dir.join("migrations"))?;
    fs::create_dir_all(dir.join("backups"))?;

    let postgres_password = util::secret(40);
    // On Docker, Postgres is the `postgres` service; on systemd, the local
    // cluster, and the image is this binary itself.
    let project = Project::new(&new.entry.name, &dir, new.runtime);
    let (db_host, image, storage_dir) = match new.runtime {
        Runtime::Docker => (
            "postgres",
            format!("NELCOTA_IMAGE={}\n", new.image),
            "/storage".to_owned(),
        ),
        Runtime::Systemd => (
            "127.0.0.1",
            String::new(),
            project.storage_dir().display().to_string(),
        ),
    };
    let env = format!(
        "# Project \"{name}\". Generated by `nelcota init` at {now}.\n\
         # CONTAINS SECRETS: mode 600, kept out of git. Keep a safe copy\n\
         # (without it, a restore on another machine invalidates the users' sessions).\n\n\
         NELCOTA_DOMAIN={domain}\n\
         {image}\
         NELCOTA_VERSION={version}\n\n\
         POSTGRES_PASSWORD={postgres_password}\n\
         NELCOTA_DATABASE_URL=postgres://postgres:{postgres_password}@{db_host}:5432/postgres\n\
         NELCOTA_AUTHENTICATOR_PASSWORD={authenticator}\n\
         NELCOTA_JWT_PRIVATE_KEY={jwt}\n\
         NELCOTA_JWT_ISSUER=https://{domain}\n\
         NELCOTA_DB_POOL_SIZE={pool}\n\
         NELCOTA_LOG_FORMAT=json\n\n\
         # File storage (docs/storage.md), on this server's disk. In production\n\
         # an S3-compatible bucket (R2, B2, AWS...) keeps files off a single disk:\n\
         NELCOTA_STORAGE_BACKEND=disk\n\
         NELCOTA_STORAGE_DIR={storage_dir}\n\
         # NELCOTA_STORAGE_BACKEND=s3\n\
         # NELCOTA_STORAGE_S3_ENDPOINT=https://<account>.r2.cloudflarestorage.com\n\
         # NELCOTA_STORAGE_S3_BUCKET=files\n\
         # NELCOTA_STORAGE_S3_ACCESS_KEY_ID=...\n\
         # NELCOTA_STORAGE_S3_SECRET_ACCESS_KEY=...\n\n\
         # Password recovery by email (optional): your provider's SMTP and the\n\
         # app page that receives the link. Then: nelcota -p {name} up\n\
         # NELCOTA_SMTP_URL=smtps://user:password@smtp.example.com:465\n\
         # NELCOTA_SMTP_FROM=Name <no-reply@{domain}>\n\
         # NELCOTA_PASSWORD_RECOVERY_URL=https://app.example.com/new-password\n\
         # Optional: confirm emails at signup and passwordless sign-in links.\n\
         # NELCOTA_EMAIL_CONFIRMATION_URL=https://app.example.com/welcome\n\
         # NELCOTA_MAGIC_LINK_URL=https://app.example.com/signed-in\n",
        name = new.entry.name,
        now = util::timestamp(),
        domain = new.entry.domain,
        version = new.version,
        authenticator = util::secret(40),
        jwt = nelcota_auth::generate_ed25519_private_key(),
        pool = pool_size(new.profile),
    );
    write_private(&dir.join(".env"), &env)?;
    if new.runtime == Runtime::Docker {
        create_storage_dir(&project.storage_dir())?;
        fs::write(
            dir.join("docker-compose.yml"),
            render_compose(&new.entry.name, new.profile),
        )?;
        pitr::write_dockerfile(&project)?;
    }
    fs::write(
        dir.join(".gitignore"),
        ".env\npgbackrest.env\nbackups/\nstorage/\n",
    )?;
    fs::write(
        dir.join("migrations/README.md"),
        "Plain SQL migrations, applied in order by `nelcota migrate`.\n\
         Names: V1__create_tables.sql, V2__add_indexes.sql, ...\n\
         Tracked in nelcota.user_migrations (version, name, checksum, date).\n",
    )?;
    Ok(())
}

/// The app container runs as 65532 (see the Dockerfile) and must own the
/// directory its files go to.
fn create_storage_dir(path: &std::path::Path) -> anyhow::Result<()> {
    fs::create_dir_all(path)?;
    #[cfg(unix)]
    std::os::unix::fs::chown(path, Some(65532), Some(65532))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn profile_by_ram_per_project() {
        assert_eq!(profile_for(960), "1gb");
        assert_eq!(profile_for(3900), "4gb");
        assert_eq!(choose_profile(None, 4096, 1).unwrap(), "4gb");
        assert_eq!(choose_profile(None, 4096, 2).unwrap(), "2gb");
        assert_eq!(choose_profile(None, 4096, 4).unwrap(), "1gb");
        assert_eq!(choose_profile(Some("2gb"), 512, 9).unwrap(), "2gb");
        assert!(choose_profile(Some("3gb"), 4096, 1).is_err());
    }

    #[test]
    fn project_compose() {
        let compose = render_compose("shop", "1gb");
        assert!(!compose.contains("{{"));
        assert!(compose.contains("name: nelcota-shop"));
        assert!(compose.contains("aliases: [app-shop]"));
        assert!(compose.contains("NELCOTA_PROJECT_NAME: shop"));
        assert!(compose.contains("      - -c\n      - shared_buffers=128MB"));
        assert!(compose.contains("internal: true"));
        assert!(compose.contains(
            "    build: ./postgres
"
        ));
        assert!(!compose.contains("ports:"), "only Caddy publishes ports");
    }
}
