//! Migration names, SQL rendering and filesystem discovery.
use std::{
    collections::BTreeMap,
    path::{Path as FsPath, PathBuf},
};

/// `V12__create_orders.sql` → `(12, "create_orders")`.
pub fn parse_filename(filename: &str) -> Option<(i32, String)> {
    let stem = filename.strip_suffix(".sql")?;
    let (version, name) = stem.strip_prefix('V')?.split_once("__")?;
    let version = version.parse().ok().filter(|v| *v > 0)?;
    Some((version, name.to_owned()))
}

/// Migration files in the project folder (empty if it does not exist).
pub(super) fn folder_migrations(dir: Option<&FsPath>) -> BTreeMap<i32, String> {
    let Some(Ok(entries)) = dir.map(std::fs::read_dir) else {
        return BTreeMap::new();
    };
    entries
        .filter_map(|e| e.ok()?.file_name().into_string().ok())
        .filter_map(|name| parse_filename(&name))
        .collect()
}

/// Generated file name: lowercase, digits and `_`, like the other migrations.
pub(super) fn valid_name(name: &str) -> bool {
    (1..=60).contains(&name.len())
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        && !name.starts_with('_')
}

/// Next free version: above everything in the database, in the folder or
/// among panel-generated ones (an unapplied file also takes its number).
pub fn next_version(taken: impl IntoIterator<Item = i32>) -> i32 {
    taken.into_iter().max().unwrap_or(0) + 1
}

/// File text. Each change becomes a block with the panel's message as a
/// comment; statements end in `;` so they run as a single batch.
pub fn render(generated_at: &str, changes: &[(String, String, Vec<String>)]) -> String {
    let mut sql = format!(
        "-- Generated by the Nelcota panel at {generated_at}.\n\
         -- Already recorded as applied in the database where it was generated:\n\
         -- put this file in migrations/ and commit it. Do not edit it (the\n\
         -- checksum would change and `nelcota migrate` would refuse it).\n"
    );
    for (applied_at, summary, statements) in changes {
        sql.push('\n');
        // Identifiers may contain CR/LF. Every line of a summary stays a
        // comment, so accepted names cannot add statements to the migration.
        for line in format!("{summary} ({applied_at})").split(['\r', '\n']) {
            sql.push_str("-- ");
            sql.push_str(line);
            sql.push('\n');
        }
        for statement in statements {
            let statement = statement.trim().trim_end_matches(';');
            sql.push_str(statement);
            sql.push_str(";\n");
        }
    }
    sql
}

/// The project's migrations folder: the configured one or, inside the
/// project container, `/migrations` (the compose file mounts it read-only).
pub fn default_dir(configured: Option<PathBuf>) -> Option<PathBuf> {
    configured.or_else(|| {
        let mounted = PathBuf::from("/migrations");
        mounted.is_dir().then_some(mounted)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_file_names() {
        assert_eq!(
            parse_filename("V12__create_orders.sql"),
            Some((12, "create_orders".into()))
        );
        assert_eq!(parse_filename("V1__a.sql"), Some((1, "a".into())));
        for bad in [
            "V0__x.sql",
            "V1_x.sql",
            "1__x.sql",
            "V1__x.txt",
            "Vx__y.sql",
            "README.md",
        ] {
            assert_eq!(parse_filename(bad), None, "{bad}");
        }
    }

    #[test]
    fn next_version_goes_past_everything_that_exists() {
        assert_eq!(next_version([]), 1);
        // Database at V3, folder with an unapplied V5: the generated one is V6.
        assert_eq!(next_version([1, 2, 3, 5]), 6);
    }

    #[test]
    fn file_name() {
        assert!(valid_name("create_orders"));
        assert!(valid_name("v2_indexes"));
        for bad in [
            "",
            "Create",
            "with space",
            "naïve",
            "_x",
            "a-b",
            &"a".repeat(61),
        ] {
            assert!(!valid_name(bad), "{bad}");
        }
    }

    #[test]
    fn file_ends_each_statement_with_a_semicolon() {
        let sql = render(
            "2026-10-07 12:00 UTC",
            &[(
                "2026-10-07 11:58 UTC".into(),
                "table 'orders' created".into(),
                vec![
                    "CREATE TABLE orders (id int)".into(),
                    "ALTER TABLE orders ENABLE ROW LEVEL SECURITY;".into(),
                ],
            )],
        );
        assert!(sql.starts_with("-- Generated by the Nelcota panel at 2026-10-07 12:00 UTC."));
        assert!(sql.contains("\n-- table 'orders' created (2026-10-07 11:58 UTC)\nCREATE TABLE orders (id int);\nALTER TABLE orders ENABLE ROW LEVEL SECURITY;\n"));
    }

    #[test]
    fn summary_line_endings_cannot_introduce_sql() {
        for separator in ["\n", "\r", "\r\n"] {
            let sql = render(
                "now",
                &[(
                    "then".into(),
                    format!("table 'x{separator}SELECT 1; --' created"),
                    vec!["SELECT 2".into()],
                )],
            );
            assert!(sql.contains("\n-- SELECT 1; --' created (then)\n"));
            assert_eq!(
                sql.lines()
                    .filter(|line| !line.is_empty() && !line.starts_with("-- "))
                    .collect::<Vec<_>>(),
                ["SELECT 2;"]
            );
        }
    }
}
