//! Connecting an app and understanding access: the TypeScript download, the
//! sign-in summary, viewing a table as someone, file access rules per bucket
//! and the log of refused API requests.
use crate::common::panel::{get, login, send};
use crate::common::*;
use axum::http::{Method, StatusCode, header};
use serde_json::{Value, json};
use uuid::Uuid;

#[tokio::test]
async fn typescript_types_download_like_nelcota_types() {
    let app = TestApp::spawn().await;
    let cookie = login(&app).await;
    let reply = get(&app, "/admin/api/typescript", &cookie).await;
    assert_eq!(reply.status, StatusCode::OK);
    assert_eq!(
        reply.headers[header::CONTENT_DISPOSITION],
        "attachment; filename=\"database.ts\""
    );
    assert!(reply.text.starts_with("// Generated by `nelcota types`"));
    assert!(reply.text.contains("export interface Database"));
    assert!(reply.text.contains("todos: {"));
    assert!(reply.text.contains("Relationships:"));
    // Behind the panel login like every panel route.
    let anonymous = app
        .raw(Method::GET, "/admin/api/typescript", &[], String::new())
        .await;
    assert_eq!(anonymous.status, StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn sign_in_summary_reflects_the_settings() {
    let app = TestApp::spawn_with(Options {
        confirm_email: true,
        ..Options::default()
    })
    .await;
    let cookie = login(&app).await;
    let reply = get(&app, "/admin/api/sign-in", &cookie).await;
    assert_eq!(reply.status, StatusCode::OK, "{}", reply.text);
    assert_eq!(reply.body["signup_enabled"], true);
    assert_eq!(reply.body["email"], true);
    assert_eq!(reply.body["email_confirmation"], true);
    assert_eq!(reply.body["magic_link"], true);
    assert_eq!(
        reply.body["providers"],
        json!({ "google": false, "github": false })
    );
    assert_eq!(reply.body["access_ttl_secs"], 900);
}

async fn signed_up(app: &TestApp, email: &str) -> (Uuid, String) {
    let reply = app
        .post(
            "/auth/v1/signup",
            None,
            json!({ "email": email, "password": "a-strong-password-1" }),
        )
        .await;
    assert_eq!(reply.status, StatusCode::CREATED, "{}", reply.text);
    let id = reply.body["user"]["id"].as_str().unwrap().parse().unwrap();
    (id, reply.body["access_token"].as_str().unwrap().to_owned())
}

#[tokio::test]
async fn tables_can_be_viewed_as_a_visitor_or_a_user() {
    let app = TestApp::spawn().await;
    let cookie = login(&app).await;
    let (ana, _) = signed_up(&app, "ana@example.com").await;
    app.admin_client
        .execute(
            "INSERT INTO public.todos (user_id, title) VALUES ($1, 'task of Ana')",
            &[&ana],
        )
        .await
        .unwrap();

    let owner = get(&app, "/admin/api/tables/todos", &cookie).await;
    assert_eq!(owner.body["rows"].as_array().unwrap().len(), 3);
    assert_eq!(owner.body["table"]["editable"], true);

    let as_ana = get(
        &app,
        &format!("/admin/api/tables/todos?as=authenticated&user={ana}"),
        &cookie,
    )
    .await;
    assert_eq!(as_ana.status, StatusCode::OK, "{}", as_ana.text);
    let titles: Vec<&str> = as_ana.body["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r["title"].as_str().unwrap())
        .collect();
    assert_eq!(titles, ["task of Ana"], "RLS shows Ana only her own rows");
    assert_eq!(as_ana.body["total"], 1);
    assert_eq!(
        as_ana.body["table"]["editable"], false,
        "viewing as someone is read-only"
    );
    assert_eq!(as_ana.body["table"]["insertable"], false);

    // Visitors have no GRANT on todos: the answer is "no access", not a failure.
    let as_visitor = get(&app, "/admin/api/tables/todos?as=anon", &cookie).await;
    assert_eq!(
        as_visitor.status,
        StatusCode::FORBIDDEN,
        "{}",
        as_visitor.text
    );
    assert_eq!(as_visitor.body["code"], "view_denied");
    assert_eq!(as_visitor.body["params"]["role"], "anon");

    // Products are readable by everyone.
    let products = get(&app, "/admin/api/tables/products?as=anon", &cookie).await;
    assert_eq!(products.status, StatusCode::OK, "{}", products.text);
    assert_eq!(products.body["rows"].as_array().unwrap().len(), 4);

    let unknown = get(
        &app,
        &format!(
            "/admin/api/tables/todos?as=authenticated&user={}",
            Uuid::new_v4()
        ),
        &cookie,
    )
    .await;
    assert_eq!(unknown.status, StatusCode::NOT_FOUND);
    let malformed = get(&app, "/admin/api/tables/todos?as=service_role", &cookie).await;
    assert_eq!(malformed.status, StatusCode::BAD_REQUEST);
    assert_eq!(malformed.body["code"], "invalid_view_as");
}

async fn access(app: &TestApp, cookie: &str, bucket: &str) -> Value {
    let reply = get(
        app,
        &format!("/admin/api/storage/buckets/{bucket}/access"),
        cookie,
    )
    .await;
    assert_eq!(reply.status, StatusCode::OK, "{}", reply.text);
    reply.body
}

async fn upload(app: &TestApp, token: &str, path: &str) -> StatusCode {
    app.bytes(
        Method::POST,
        &format!("/storage/v1/object/{path}"),
        Some(token),
        &[("content-type", "text/plain")],
        b"hello".to_vec(),
    )
    .await
    .0
}

#[tokio::test]
async fn bucket_access_rules_from_templates() {
    let app = TestApp::spawn().await;
    let cookie = login(&app).await;
    for id in ["avatars", "docs"] {
        let created = send(
            &app,
            Method::POST,
            "/admin/api/storage/buckets",
            &cookie,
            json!({ "id": id }),
        )
        .await;
        assert_eq!(created.status, StatusCode::CREATED, "{}", created.text);
    }
    assert_eq!(
        access(&app, &cookie, "avatars").await["policies"],
        json!([])
    );

    let (ana, ana_token) = signed_up(&app, "ana@example.com").await;
    assert_ne!(
        upload(&app, &ana_token, &format!("avatars/{ana}/me.txt"))
            .await
            .as_u16()
            / 100,
        2
    );

    // Preview first: the SQL, nothing applied.
    let preview = send(
        &app,
        Method::POST,
        "/admin/api/storage/buckets/avatars/access",
        &cookie,
        json!({ "template": "own_folder", "preview": true }),
    )
    .await;
    assert_eq!(preview.status, StatusCode::OK, "{}", preview.text);
    assert_eq!(preview.body["applied"], false);
    assert!(
        preview.body["sql"][0]
            .as_str()
            .unwrap()
            .contains("storage.foldername(name)")
    );

    let created = send(
        &app,
        Method::POST,
        "/admin/api/storage/buckets/avatars/access",
        &cookie,
        json!({ "template": "own_folder" }),
    )
    .await;
    assert_eq!(created.status, StatusCode::OK, "{}", created.text);
    let rules = access(&app, &cookie, "avatars").await;
    assert_eq!(rules["public"], false);
    let policy = &rules["policies"][0];
    assert_eq!(policy["name"], "avatars_own_folder");
    assert_eq!(policy["command"], "ALL");
    assert_eq!(policy["all_buckets"], false);
    // Postgres prints the expression back with casts; the panel reads this form.
    let using = policy["using"].as_str().unwrap();
    assert!(using.contains("bucket_id = 'avatars'::text"), "{using}");
    assert!(using.contains("storage.foldername(name)"), "{using}");
    assert_eq!(
        access(&app, &cookie, "docs").await["policies"],
        json!([]),
        "scoped to avatars"
    );

    assert_eq!(
        upload(&app, &ana_token, &format!("avatars/{ana}/me.txt")).await,
        StatusCode::CREATED
    );
    let other = Uuid::new_v4();
    assert_ne!(
        upload(&app, &ana_token, &format!("avatars/{other}/x.txt")).await,
        StatusCode::CREATED
    );

    // A policy that names no bucket covers every bucket.
    app.admin_client
        .batch_execute(
            "CREATE POLICY everyone_reads ON storage.objects FOR SELECT TO anon USING (true)",
        )
        .await
        .unwrap();
    let docs = access(&app, &cookie, "docs").await;
    assert_eq!(docs["policies"][0]["name"], "everyone_reads");
    assert_eq!(docs["policies"][0]["all_buckets"], true);

    // Recorded for "Generate migration", then dropped.
    let changes: i64 = app
        .admin_client
        .query_one(
            "SELECT count(*) FROM nelcota.panel_changes WHERE target = 'avatars_own_folder'",
            &[],
        )
        .await
        .unwrap()
        .get(0);
    assert_eq!(changes, 1);
    let dropped = send(
        &app,
        Method::DELETE,
        "/admin/api/storage/buckets/avatars/access/avatars_own_folder",
        &cookie,
        json!(null),
    )
    .await;
    assert_eq!(dropped.status, StatusCode::OK, "{}", dropped.text);
    let left: Vec<Value> = access(&app, &cookie, "avatars").await["policies"]
        .as_array()
        .unwrap()
        .clone();
    assert_eq!(left.len(), 1, "only the all-buckets policy is left");

    let missing = send(
        &app,
        Method::POST,
        "/admin/api/storage/buckets/nope/access",
        &cookie,
        json!({ "template": "public_read" }),
    )
    .await;
    assert_eq!(missing.status, StatusCode::NOT_FOUND);
}

#[tokio::test]
async fn refused_api_requests_are_listed_for_the_panel() {
    let app = TestApp::spawn().await;
    let cookie = login(&app).await;
    let (ana, ana_token) = signed_up(&app, "ana@example.com").await;

    // Allowed requests and the panel's own routes are not recorded.
    assert_eq!(app.get("/rest/v1/products", None).await.0, StatusCode::OK);
    assert_eq!(
        get(&app, "/admin/api/denied", &cookie).await.body["requests"],
        json!([])
    );

    // A visitor without a GRANT, a write RLS refuses, and a bad token.
    assert_eq!(
        app.get("/rest/v1/todos?title=eq.secret", None).await.0,
        StatusCode::UNAUTHORIZED
    );
    let other = Uuid::new_v4();
    let refused = app
        .post(
            "/rest/v1/todos",
            Some(&ana_token),
            json!({ "title": "not mine", "user_id": other }),
        )
        .await;
    assert_eq!(refused.status, StatusCode::FORBIDDEN, "{}", refused.text);
    assert_eq!(
        app.get("/rest/v1/todos", Some("not-a-jwt")).await.0,
        StatusCode::UNAUTHORIZED
    );

    let reply = get(&app, "/admin/api/denied", &cookie).await;
    assert_eq!(reply.status, StatusCode::OK, "{}", reply.text);
    let requests = reply.body["requests"].as_array().unwrap();
    assert_eq!(requests.len(), 3, "{requests:?}");
    // Newest first.
    assert_eq!(requests[0]["role"], "invalid_token");
    assert_eq!(requests[0]["code"], "invalid_token");

    let write = &requests[1];
    assert_eq!(write["method"], "POST");
    assert_eq!(write["path"], "/rest/v1/todos");
    assert_eq!(write["status"], 403);
    assert_eq!(write["role"], "authenticated");
    assert_eq!(write["user_id"], ana.to_string());
    assert!(
        write["message"]
            .as_str()
            .unwrap()
            .contains("row-level security"),
        "{write}"
    );

    let read = &requests[2];
    assert_eq!(read["role"], "anon");
    assert_eq!(read["status"], 401);
    assert_eq!(read["code"], "db_error");
    assert_eq!(
        read["path"], "/rest/v1/todos",
        "the query string is never kept"
    );
    assert!(read["at"].as_str().unwrap().ends_with('Z'));
    assert_eq!(reply.body["capacity"], 100);
}
