-- Schema the SDK contract tests run against (scripts/contract.mjs applies it).

CREATE TYPE public.order_status AS ENUM ('open', 'paid', 'shipped');

CREATE TABLE public.customers (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE public.orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner       uuid NOT NULL DEFAULT auth.uid(),
    customer_id bigint REFERENCES public.customers (id),
    status      public.order_status NOT NULL DEFAULT 'open',
    total       numeric(10,2) NOT NULL DEFAULT 0,
    note        text
);

CREATE TABLE public.items (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders (id) ON DELETE CASCADE,
    product  text NOT NULL,
    qty      integer NOT NULL DEFAULT 1
);
CREATE INDEX ON public.items (order_id);

-- Free text values for the encoder round trip.
CREATE TABLE public.echo (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner uuid NOT NULL DEFAULT auth.uid(),
    value text NOT NULL,
    slug  text UNIQUE
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.echo ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.customers TO anon, authenticated;
CREATE POLICY customers_read ON public.customers FOR SELECT TO anon, authenticated USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders, public.items, public.echo TO authenticated;
CREATE POLICY orders_owner ON public.orders FOR ALL TO authenticated
    USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());
CREATE POLICY items_owner ON public.items FOR ALL TO authenticated
    USING (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.owner = auth.uid()))
    WITH CHECK (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.owner = auth.uid()));
CREATE POLICY echo_owner ON public.echo FOR ALL TO authenticated
    USING (owner = auth.uid()) WITH CHECK (owner = auth.uid());

INSERT INTO public.customers (name) VALUES ('Ana'), ('Bruno'), ('Ruler, "30cm" (wood)');

CREATE FUNCTION public.add(a integer, b integer DEFAULT 10) RETURNS integer
    LANGUAGE sql IMMUTABLE AS $$ SELECT a + b $$;
CREATE FUNCTION public.whoami() RETURNS text
    LANGUAGE sql STABLE AS $$ SELECT coalesce(auth.uid()::text, 'anon') $$;
CREATE FUNCTION public.nothing() RETURNS void LANGUAGE sql AS $$ SELECT $$;
GRANT EXECUTE ON FUNCTION public.add(integer, integer), public.whoami(), public.nothing() TO anon, authenticated;

-- Files: each user writes into the folder named after their id.
INSERT INTO storage.buckets (id, public) VALUES ('private-files', false), ('public-files', true);
CREATE POLICY files_owner ON storage.objects FOR ALL TO authenticated
    USING ((storage.foldername(name))[1] = auth.uid()::text)
    WITH CHECK ((storage.foldername(name))[1] = auth.uid()::text);
