-- API test fixture: assorted types, a public table without RLS, and functions.
-- Applied after examples/todos.sql.

CREATE TYPE public.priority AS ENUM ('low', 'medium', 'high');

ALTER TABLE public.todos
    ADD COLUMN priority public.priority NOT NULL DEFAULT 'medium',
    ADD COLUMN tags text[] NOT NULL DEFAULT '{}',
    ADD COLUMN extra jsonb;

-- Public catalog: readable by everyone, writable only by service_role. No RLS
-- on purpose (the panel must warn about it).
CREATE TABLE public.products (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(80)   NOT NULL,
    price      numeric(10,2) NOT NULL CHECK (price >= 0),
    stock      integer       NOT NULL DEFAULT 0,
    created_at timestamptz   NOT NULL DEFAULT now(),
    slug       text GENERATED ALWAYS AS (lower(name)) STORED
);
COMMENT ON TABLE public.products IS 'Product catalog';
GRANT SELECT ON public.products TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO service_role;

INSERT INTO public.products (name, price, stock) VALUES
    ('Pen', 2.50, 100),
    ('Notebook', 15.00, 20),
    ('Backpack', 120.00, 0),
    ('Ruler, 30cm', 4.00, 50);

-- Table for service_role only (no GRANT for anon/authenticated).
CREATE TABLE public.secrets (id int PRIMARY KEY, value text);
GRANT SELECT ON public.secrets TO service_role;

CREATE FUNCTION public.my_open_todos() RETURNS SETOF public.todos
    LANGUAGE sql STABLE AS $$ SELECT * FROM public.todos WHERE NOT done ORDER BY id $$;

CREATE FUNCTION public.add(a integer, b integer DEFAULT 10) RETURNS integer
    LANGUAGE sql IMMUTABLE AS $$ SELECT a + b $$;

CREATE FUNCTION public.who_am_i() RETURNS json
    LANGUAGE sql STABLE AS $$ SELECT json_build_object('uid', auth.uid(), 'role', auth.role()) $$;

CREATE FUNCTION public.nothing() RETURNS void
    LANGUAGE sql AS $$ SELECT $$;

CREATE FUNCTION public.fail() RETURNS integer
    LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'business rule violated'; END $$;

CREATE FUNCTION public.service_only() RETURNS text
    LANGUAGE sql AS $$ SELECT 'ok' $$;
REVOKE EXECUTE ON FUNCTION public.service_only() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.service_only() TO service_role;
