-- Fixture dos testes da API: tipos variados, tabela pública sem RLS e funções.
-- Aplicada depois de examples/todos.sql.

CREATE TYPE public.prioridade AS ENUM ('baixa', 'media', 'alta');

ALTER TABLE public.todos
    ADD COLUMN prioridade public.prioridade NOT NULL DEFAULT 'media',
    ADD COLUMN tags text[] NOT NULL DEFAULT '{}',
    ADD COLUMN extra jsonb;

-- Catálogo público: leitura para todos, escrita só para service_role. Sem RLS
-- de propósito (o painel deve alertar).
CREATE TABLE public.produtos (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      varchar(80)   NOT NULL,
    preco     numeric(10,2) NOT NULL CHECK (preco >= 0),
    estoque   integer       NOT NULL DEFAULT 0,
    criado_em timestamptz   NOT NULL DEFAULT now(),
    slug      text GENERATED ALWAYS AS (lower(nome)) STORED
);
COMMENT ON TABLE public.produtos IS 'Catálogo de produtos';
GRANT SELECT ON public.produtos TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.produtos TO service_role;

INSERT INTO public.produtos (nome, preco, estoque) VALUES
    ('Caneta', 2.50, 100),
    ('Caderno', 15.00, 20),
    ('Mochila', 120.00, 0),
    ('Régua, 30cm', 4.00, 50);

-- Tabela só para service_role (nenhum GRANT para anon/authenticated).
CREATE TABLE public.segredos (id int PRIMARY KEY, valor text);
GRANT SELECT ON public.segredos TO service_role;

CREATE FUNCTION public.minhas_tarefas_abertas() RETURNS SETOF public.todos
    LANGUAGE sql STABLE AS $$ SELECT * FROM public.todos WHERE NOT done ORDER BY id $$;

CREATE FUNCTION public.soma(a integer, b integer DEFAULT 10) RETURNS integer
    LANGUAGE sql IMMUTABLE AS $$ SELECT a + b $$;

CREATE FUNCTION public.quem_sou_eu() RETURNS json
    LANGUAGE sql STABLE AS $$ SELECT json_build_object('uid', auth.uid(), 'role', auth.role()) $$;

CREATE FUNCTION public.nada() RETURNS void
    LANGUAGE sql AS $$ SELECT $$;

CREATE FUNCTION public.falha() RETURNS integer
    LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'regra de negócio violada'; END $$;

CREATE FUNCTION public.so_servico() RETURNS text
    LANGUAGE sql AS $$ SELECT 'ok' $$;
REVOKE EXECUTE ON FUNCTION public.so_servico() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.so_servico() TO service_role;
