//! Runs the DDL generated by the panel, or only returns its preview.

use axum::Json;
use serde_json::{Value, json};

use crate::{AdminState, ApiError, api::user_query_error};

/// With `preview`, returns the SQL without running it. Without, runs it all in
/// one transaction and reloads the catalog before answering: the caller
/// already sees the new table/column in the API (no waiting for NOTIFY).
///
/// Each statement goes through the extended protocol (`execute`), which
/// refuses more than one statement at a time: an expression such as
/// `true); DROP TABLE x; --` fails instead of running what follows.
pub async fn apply(
    state: &AdminState,
    statements: Vec<String>,
    preview: bool,
    message: &str,
) -> Result<Json<Value>, ApiError> {
    if preview {
        return Ok(Json(json!({ "sql": statements })));
    }
    {
        let mut client = state.db.get().await?;
        let tx = client.transaction().await?;
        for statement in &statements {
            tx.execute(statement.as_str(), &[])
                .await
                .map_err(user_query_error)?;
        }
        // Record for "Generate migration" (see migrations.rs), in the same
        // transaction: a failed DDL is not recorded, and vice versa.
        tx.execute(
            "INSERT INTO nelcota.panel_changes (summary, statements) VALUES ($1, $2)",
            &[&message, &statements],
        )
        .await?;
        tx.commit().await.map_err(user_query_error)?;
        // The connection returns to the pool here; the reload uses another one.
    }
    // The DDL text does not go to the log (it may contain data), only its size.
    tracing::info!(statements = statements.len(), "DDL applied by the panel");
    state
        .catalog
        .reload(&state.db)
        .await
        .map_err(|e| ApiError::from(format!("DDL applied, but the catalog did not reload: {e}")))?;
    Ok(Json(json!({ "message": message, "sql": statements })))
}
