//! Runs the DDL generated by the panel, or only returns its preview.

use axum::Json;

use crate::{AdminState, ApiError, api::user_query_error};

/// What a DDL batch did. Recorded in `nelcota.panel_changes` as kind and
/// target, so the panel describes the change in the viewer's language; the
/// English summary goes into generated migration files and API responses.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ChangeKind {
    TableCreated,
    TableAltered,
    TableDropped,
    PolicyCreated,
    PolicyUpdated,
    PolicyDropped,
}

impl ChangeKind {
    /// Value of `panel_changes.kind` (CHECK constraint in migration V7).
    pub fn code(self) -> &'static str {
        match self {
            ChangeKind::TableCreated => "table_created",
            ChangeKind::TableAltered => "table_altered",
            ChangeKind::TableDropped => "table_dropped",
            ChangeKind::PolicyCreated => "policy_created",
            ChangeKind::PolicyUpdated => "policy_updated",
            ChangeKind::PolicyDropped => "policy_dropped",
        }
    }

    pub fn summary(self, target: &str) -> String {
        let (object, verb) = match self {
            ChangeKind::TableCreated => ("table", "created"),
            ChangeKind::TableAltered => ("table", "altered"),
            ChangeKind::TableDropped => ("table", "dropped"),
            ChangeKind::PolicyCreated => ("policy", "created"),
            ChangeKind::PolicyUpdated => ("policy", "updated"),
            ChangeKind::PolicyDropped => ("policy", "dropped"),
        };
        format!("{object} '{target}' {verb}")
    }
}

/// With `preview`, returns the SQL without running it. Without, runs it all in
/// one transaction and attempts to refresh the catalog before answering.
/// A post-commit introspection failure is reported as catalog_pending and retried.
///
/// Each statement goes through the extended protocol (`execute`), which
/// refuses more than one statement at a time: an expression such as
/// `true); DROP TABLE x; --` fails instead of running what follows.
pub async fn apply(
    state: &AdminState,
    statements: Vec<String>,
    preview: bool,
    kind: ChangeKind,
    target: &str,
) -> Result<Json<crate::contracts::DdlResult>, ApiError> {
    if preview {
        return Ok(Json(crate::contracts::DdlResult {
            sql: statements,
            ..Default::default()
        }));
    }
    let message = kind.summary(target);
    {
        let mut client = state.db.get().await?;
        let tx = client.transaction().await?;
        for statement in &statements {
            tx.execute(statement.as_str(), &[])
                .await
                .map_err(user_query_error)?;
        }
        // Record for "Generate migration" (see migrations.rs), in the same
        // transaction: a failed DDL is not recorded, and vice versa.
        tx.execute(
            "INSERT INTO nelcota.panel_changes (summary, statements, kind, target)
             VALUES ($1, $2, $3, $4)",
            &[&message, &statements, &kind.code(), &target],
        )
        .await?;
        tx.commit().await.map_err(user_query_error)?;
        // The connection returns to the pool here; the reload uses another one.
    }
    // The DDL text does not go to the log (it may contain data), only its size.
    tracing::info!(statements = statements.len(), "DDL applied by the panel");
    let ready = state.catalog.refresh(&state.db).await;
    Ok(Json(crate::contracts::DdlResult {
        message: Some(message),
        sql: statements,
        applied: true,
        catalog_pending: !ready,
    }))
}

#[cfg(test)]
mod tests {
    use super::ChangeKind;

    #[test]
    fn summary_matches_the_v7_backfill_patterns() {
        // V7 recovers kind/target from summaries in this exact shape.
        assert_eq!(
            ChangeKind::TableCreated.summary("orders"),
            "table 'orders' created"
        );
        assert_eq!(
            ChangeKind::PolicyUpdated.summary("owner reads"),
            "policy 'owner reads' updated"
        );
        assert_eq!(ChangeKind::PolicyDropped.code(), "policy_dropped");
    }
}
