//! Admin panel at `/admin`.
//!
//! - Frontend: a Svelte 5 SPA (`crates/admin/ui`), built with Vite into
//!   `ui/dist` and embedded in the binary (`rust-embed`). No Node in production.
//! - Backend: a JSON API under `/admin/api/*`, behind its own login
//!   (`NELCOTA_ADMIN_EMAIL` + argon2id hash), separate from end users.
//!   In-memory sessions, `HttpOnly; SameSite=Strict` cookie, and an origin
//!   check on every state-changing request (CSRF).
//! - The panel talks to the database over the admin connection: the admin
//!   sees and changes everything, as in `psql`. Table writes reuse the API's
//!   SQL builder (identifiers only from the catalog, values as parameters).

mod api;
mod apply;
pub mod contracts;
mod ddl;
mod export;
mod migrations;
mod policies_ddl;
mod profile;
mod projects;
mod sql;
mod sso;
mod storage;
mod structure;
mod tables_ddl;
mod tokens;
mod users;

pub use migrations::default_dir as default_migrations_dir;
pub use projects::HostLink;
pub use sql::SqlExecutor;
pub use sso::Sso;
pub use tokens::TokenIssuer;

use std::{
    collections::HashMap,
    sync::{Arc, Mutex},
    time::{Duration, Instant},
};

use axum::{
    Json, Router,
    body::Body,
    extract::{Path, Request, State},
    http::{HeaderMap, HeaderValue, Method, StatusCode, header},
    middleware::{self, Next},
    response::{IntoResponse, Redirect, Response},
    routing::{delete, get, post, put},
};
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use cookie::{Cookie, SameSite};
use deadpool_postgres::Pool;
use nelcota_api::CatalogHandle;
use nelcota_auth::RateLimiter;
use rust_embed::RustEmbed;
use serde::Deserialize;
use serde_json::json;
use sha2::{Digest, Sha256};

const COOKIE: &str = "nelcota_admin";
const SESSION_TTL: Duration = Duration::from_secs(12 * 3600);

/// Frontend build (`npm run build` in `crates/admin/ui`).
#[derive(RustEmbed)]
#[folder = "ui/dist/"]
struct Ui;

pub struct Credentials {
    pub email: String,
    pub password_hash: String,
}

/// In-memory panel sessions (key = SHA-256 of the cookie token).
#[derive(Default)]
pub struct Sessions {
    active: Mutex<HashMap<Vec<u8>, Instant>>,
}

impl Sessions {
    fn create(&self) -> String {
        let mut bytes = [0u8; 32];
        getrandom::fill(&mut bytes).expect("system randomness source unavailable");
        let token = URL_SAFE_NO_PAD.encode(bytes);
        let mut active = self.active.lock().unwrap_or_else(|e| e.into_inner());
        let now = Instant::now();
        active.retain(|_, expires| *expires > now);
        active.insert(Sha256::digest(token.as_bytes()).to_vec(), now + SESSION_TTL);
        token
    }

    fn valid(&self, token: &str) -> bool {
        let active = self.active.lock().unwrap_or_else(|e| e.into_inner());
        active
            .get(&Sha256::digest(token.as_bytes())[..])
            .is_some_and(|expires| *expires > Instant::now())
    }

    fn remove(&self, token: &str) {
        let mut active = self.active.lock().unwrap_or_else(|e| e.into_inner());
        active.remove(&Sha256::digest(token.as_bytes())[..]);
    }
}

#[derive(Clone)]
pub struct AdminState {
    /// Bounded SQL executions shared by all panel sessions.
    pub sql: Arc<SqlExecutor>,
    /// Admin pool (role that owns the schema).
    pub db: Pool,
    /// Admin config, for the SQL editor's dedicated connections.
    pub db_config: tokio_postgres::Config,
    pub catalog: Arc<CatalogHandle>,
    pub credentials: Arc<Credentials>,
    pub sessions: Arc<Sessions>,
    pub limiter: Arc<RateLimiter>,
    /// Cookie with `Secure` (behind Caddy/HTTPS).
    pub secure_cookies: bool,
    /// Current project, the host's project list and single sign-on.
    pub host: Arc<HostLink>,
    /// service_role token issuing from the API page.
    pub tokens: Arc<TokenIssuer>,
    /// The project's `migrations/` folder, when reachable (so migrations
    /// generated by the panel never collide with unapplied files).
    pub migrations_dir: Option<std::path::PathBuf>,
    /// File storage, when a backend is configured.
    pub storage: Option<nelcota_storage::StorageState>,
}

pub fn router(state: AdminState) -> Router {
    let protected = Router::new()
        .route("/admin/api/session", get(session))
        .route("/admin/api/logout", post(logout))
        .route("/admin/api/overview", get(api::overview))
        .route("/admin/api/schema", get(api::schema))
        .route("/admin/api/types", get(tables_ddl::types))
        .route(
            "/admin/api/tables",
            get(api::tables).post(tables_ddl::create),
        )
        .route(
            "/admin/api/tables/{name}",
            get(api::table)
                .patch(tables_ddl::alter)
                .delete(tables_ddl::drop),
        )
        .route("/admin/api/tables/{name}/export", get(export::export))
        .route(
            "/admin/api/tables/{name}/structure",
            get(structure::structure),
        )
        .route(
            "/admin/api/tables/{name}/rows",
            post(api::insert_row)
                .patch(api::update_row)
                .delete(api::delete_rows),
        )
        .route("/admin/api/sql", post(sql::run))
        .route("/admin/api/users", get(api::users).post(users::create))
        .route("/admin/api/users/{id}/password", put(users::set_password))
        .route("/admin/api/users/{id}/revoke", post(api::revoke_sessions))
        .route("/admin/api/users/{id}", delete(api::delete_user))
        .route("/admin/api/policies", get(api::policies))
        .route(
            "/admin/api/tables/{name}/policies",
            post(policies_ddl::create),
        )
        .route(
            "/admin/api/tables/{name}/policies/{policy}",
            put(policies_ddl::replace).delete(policies_ddl::drop),
        )
        .route("/admin/api/projects", get(projects::list))
        .route("/admin/api/projects/status", get(projects::status))
        .route("/admin/api/sso/handoff", post(sso::handoff))
        .route("/admin/api/tokens/service-role", post(tokens::service_role))
        .route(
            "/admin/api/migrations",
            get(migrations::list).post(migrations::export),
        )
        .route(
            "/admin/api/migrations/{version}/file",
            get(migrations::file),
        )
        .route("/admin/api/storage", get(storage::overview))
        .route("/admin/api/storage/buckets", post(storage::create_bucket))
        .route(
            "/admin/api/storage/buckets/{id}",
            put(storage::update_bucket).delete(storage::delete_bucket),
        )
        .route(
            "/admin/api/storage/buckets/{id}/objects",
            get(storage::list),
        )
        .route(
            "/admin/api/storage/buckets/{id}/file",
            get(storage::download).delete(storage::delete),
        )
        .route("/admin/api/profile", get(profile::get))
        .route(
            "/admin/api/profile/avatar",
            get(profile::image)
                .put(profile::upload)
                .delete(profile::remove),
        )
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            require_session,
        ));

    Router::new()
        .route("/admin/api/login", post(login))
        .route("/admin/api/sso", post(sso::redeem))
        .route("/admin/api/whoami", get(whoami))
        .merge(protected)
        .route("/admin/api/{*rest}", get(api_not_found).post(api_not_found))
        .route("/admin/assets/{*file}", get(asset))
        .route("/admin", get(|| async { Redirect::to("/admin/") }))
        .route("/admin/", get(spa))
        .route("/admin/{*route}", get(spa))
        .layer(middleware::from_fn(same_origin))
        .layer(middleware::from_fn(security_headers))
        .with_state(state)
}

/// The panel's file upload, on its own so the server can mount it outside
/// the request timeout and body limit, like the storage API (D78).
pub fn upload_router(state: AdminState) -> Router {
    Router::new()
        .route(
            "/admin/api/storage/buckets/{id}/upload",
            post(storage::upload),
        )
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            require_session,
        ))
        .layer(axum::extract::DefaultBodyLimit::disable())
        .layer(middleware::from_fn(same_origin))
        .layer(middleware::from_fn(security_headers))
        .with_state(state)
}

/// Panel API error: `{"error": "<English text>", "code": "...", "params": {...}}`.
///
/// `code` and `params` let the panel show the error in the user's language
/// (crates/admin/ui/src/lib/i18n/messages/errors.ts); `error` stays the
/// English text for other API consumers. Errors that come straight from
/// Postgres carry no code, so the panel shows their text as-is.
#[derive(Debug)]
pub struct ApiError {
    status: StatusCode,
    message: String,
    code: Option<&'static str>,
    params: Option<serde_json::Value>,
}

impl ApiError {
    pub fn new(status: StatusCode, code: &'static str, message: impl Into<String>) -> Self {
        ApiError {
            status,
            message: message.into(),
            code: Some(code),
            params: None,
        }
    }

    pub fn bad_request(code: &'static str, message: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, code, message)
    }

    pub fn not_found(code: &'static str, message: impl Into<String>) -> Self {
        Self::new(StatusCode::NOT_FOUND, code, message)
    }

    pub fn conflict(code: &'static str, message: impl Into<String>) -> Self {
        Self::new(StatusCode::CONFLICT, code, message)
    }

    /// Values for the placeholders of the translated message.
    pub fn params(mut self, params: serde_json::Value) -> Self {
        self.params = Some(params);
        self
    }

    /// Error without a code, shown verbatim (e.g. a Postgres message).
    pub fn raw(status: StatusCode, message: impl Into<String>) -> Self {
        ApiError {
            status,
            message: message.into(),
            code: None,
            params: None,
        }
    }
}

/// Any other error (database, pool, JSON) becomes a 500 with its message: the
/// admin owns the database and needs the text to act on it.
impl<E: std::fmt::Display> From<E> for ApiError {
    fn from(err: E) -> Self {
        ApiError::raw(StatusCode::INTERNAL_SERVER_ERROR, err.to_string())
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        let mut body = json!({ "error": self.message });
        if let Some(code) = self.code {
            body["code"] = json!(code);
        }
        if let Some(params) = self.params {
            body["params"] = params;
        }
        (self.status, Json(body)).into_response()
    }
}

async fn api_not_found() -> ApiError {
    ApiError::not_found("route_not_found", "route not found")
}

fn session_token(headers: &HeaderMap) -> Option<String> {
    headers
        .get_all(header::COOKIE)
        .iter()
        .filter_map(|v| v.to_str().ok())
        .flat_map(Cookie::split_parse)
        .filter_map(Result::ok)
        .find(|c| c.name() == COOKIE)
        .map(|c| c.value().to_owned())
}

/// The panel session cookie: `HttpOnly`, `SameSite=Strict`, limited to
/// `/admin`, and `Secure` behind HTTPS. An empty value with a zero max age
/// clears it.
fn session_cookie(value: String, max_age: cookie::time::Duration, secure: bool) -> String {
    Cookie::build((COOKIE, value))
        .path("/admin")
        .http_only(true)
        .same_site(SameSite::Strict)
        .secure(secure)
        .max_age(max_age)
        .build()
        .to_string()
}

async fn require_session(
    State(state): State<AdminState>,
    request: Request,
    next: Next,
) -> Response {
    let ok = session_token(request.headers()).is_some_and(|t| state.sessions.valid(&t));
    if ok {
        next.run(request).await
    } else {
        ApiError::new(
            StatusCode::UNAUTHORIZED,
            "session_expired",
            "session expired: sign in again",
        )
        .into_response()
    }
}

/// CSRF defence on top of `SameSite=Strict`: state-changing requests must come
/// from the same origin (browsers always send `Origin` on POST).
async fn same_origin(request: Request, next: Next) -> Response {
    if request.method() != Method::GET && request.method() != Method::HEAD {
        let headers = request.headers();
        let host = headers.get(header::HOST).and_then(|v| v.to_str().ok());
        if let Some(origin) = headers.get(header::ORIGIN).and_then(|v| v.to_str().ok()) {
            let matches = host.is_some_and(|host| {
                origin == format!("https://{host}") || origin == format!("http://{host}")
            });
            if !matches {
                return forbidden_origin();
            }
        }
        if headers
            .get("sec-fetch-site")
            .is_some_and(|v| v == "cross-site")
        {
            return forbidden_origin();
        }
    }
    next.run(request).await
}

fn forbidden_origin() -> Response {
    ApiError::new(
        StatusCode::FORBIDDEN,
        "origin_not_allowed",
        "origin not allowed",
    )
    .into_response()
}

async fn security_headers(request: Request, next: Next) -> Response {
    let mut response = next.run(request).await;
    let headers = response.headers_mut();
    // Scripts only from this server. Inline styles are allowed because
    // Svelte transitions, CodeMirror and menu positioning (floating-ui)
    // inject styles at runtime.
    // A file downloaded through the panel keeps its own (sandboxed) policy.
    headers
        .entry(header::CONTENT_SECURITY_POLICY)
        .or_insert(HeaderValue::from_static(
            "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; \
             img-src 'self' data:; font-src 'self'; connect-src 'self'; \
             frame-ancestors 'none'; form-action 'self'; base-uri 'none'",
        ));
    headers.insert(header::X_FRAME_OPTIONS, HeaderValue::from_static("DENY"));
    headers.insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    // `same-origin`, not `no-referrer`: with `no-referrer` the browser sends
    // `Origin: null` on POSTs and the CSRF check would reject the panel itself.
    headers.insert(
        header::REFERRER_POLICY,
        HeaderValue::from_static("same-origin"),
    );
    headers
        .entry(header::CACHE_CONTROL)
        .or_insert(HeaderValue::from_static("no-store"));
    response
}

fn content_type(path: &str) -> &'static str {
    match path.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        Some("png") => "image/png",
        _ => "application/octet-stream",
    }
}

fn ui_file(path: &str) -> Response {
    let Some(file) = Ui::get(path) else {
        return StatusCode::NOT_FOUND.into_response();
    };
    (
        [(header::CONTENT_TYPE, content_type(path))],
        Body::from(file.data.into_owned()),
    )
        .into_response()
}

/// Files with a hash in their name (built by Vite): long, immutable cache.
async fn asset(Path(file): Path<String>) -> Response {
    let mut response = ui_file(&format!("assets/{file}"));
    if response.status().is_success() {
        response.headers_mut().insert(
            header::CACHE_CONTROL,
            HeaderValue::from_static("public, max-age=31536000, immutable"),
        );
    }
    response
}

/// Every panel route returns the SPA's `index.html` (client-side routing).
/// The page itself holds no data: everything comes from the authenticated API.
async fn spa() -> Response {
    let mut response = ui_file("index.html");
    response
        .headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static("no-cache"));
    response
}

#[derive(Deserialize)]
struct LoginRequest {
    email: String,
    password: String,
}

async fn login(State(state): State<AdminState>, Json(form): Json<LoginRequest>) -> Response {
    if state.limiter.check("admin-login").is_err() {
        return ApiError::new(
            StatusCode::TOO_MANY_REQUESTS,
            "too_many_attempts",
            "Too many attempts. Wait a minute.",
        )
        .into_response();
    }
    // The password is always checked (even with a wrong email), so response
    // time does not reveal which of the two failed.
    let hash = state.credentials.password_hash.clone();
    let password = form.password;
    let password_ok =
        tokio::task::spawn_blocking(move || nelcota_auth::verify_password(&password, &hash))
            .await
            .unwrap_or(false);
    let email_ok = form
        .email
        .trim()
        .eq_ignore_ascii_case(&state.credentials.email);
    if !(password_ok && email_ok) {
        tracing::warn!("panel login refused");
        return ApiError::new(
            StatusCode::UNAUTHORIZED,
            "invalid_credentials",
            "Invalid email or password.",
        )
        .into_response();
    }
    tracing::info!("panel login");
    (
        [(header::SET_COOKIE, new_session_cookie(&state))],
        Json(json!({ "email": state.credentials.email })),
    )
        .into_response()
}

/// Creates a session and returns the matching `Set-Cookie`.
fn new_session_cookie(state: &AdminState) -> String {
    let ttl = i64::try_from(SESSION_TTL.as_secs()).unwrap_or(i64::MAX);
    session_cookie(
        state.sessions.create(),
        cookie::time::Duration::seconds(ttl),
        state.secure_cookies,
    )
}

/// `GET /admin/api/whoami` (public): project name, for the login screen.
async fn whoami(State(state): State<AdminState>) -> Json<serde_json::Value> {
    Json(json!({ "project": state.host.project, "sso": state.host.sso.is_some() }))
}

async fn session(State(state): State<AdminState>) -> Json<serde_json::Value> {
    Json(json!({ "email": state.credentials.email, "project": state.host.project }))
}

async fn logout(State(state): State<AdminState>, headers: HeaderMap) -> Response {
    if let Some(token) = session_token(&headers) {
        state.sessions.remove(&token);
    }
    (
        [(
            header::SET_COOKIE,
            session_cookie(
                String::new(),
                cookie::time::Duration::ZERO,
                state.secure_cookies,
            ),
        )],
        Json(json!({ "ok": true })),
    )
        .into_response()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn headers(values: &[&str]) -> HeaderMap {
        let mut map = HeaderMap::new();
        for v in values {
            map.append(header::COOKIE, HeaderValue::from_str(v).unwrap());
        }
        map
    }

    #[test]
    fn session_token_finds_the_panel_cookie() {
        let token = |values: &[&str]| session_token(&headers(values));
        assert_eq!(token(&["nelcota_admin=abc"]).as_deref(), Some("abc"));
        assert_eq!(
            token(&["theme=dark; nelcota_admin=abc;  other=1"]).as_deref(),
            Some("abc")
        );
        // Several Cookie headers (HTTP/2 splits them).
        assert_eq!(
            token(&["theme=dark", "nelcota_admin=xyz"]).as_deref(),
            Some("xyz")
        );
        // A cookie whose name only starts the same way does not count.
        assert_eq!(token(&["nelcota_admin_old=abc"]), None);
        assert_eq!(token(&["garbage; =; ;"]), None);
        assert_eq!(token(&[]), None);
    }

    #[test]
    fn session_cookie_carries_the_security_attributes() {
        let set = session_cookie("tok".into(), cookie::time::Duration::seconds(60), true);
        let parsed = Cookie::parse(set.clone()).unwrap();
        assert_eq!((parsed.name(), parsed.value()), (COOKIE, "tok"));
        assert_eq!(parsed.path(), Some("/admin"));
        assert_eq!(parsed.http_only(), Some(true));
        assert_eq!(parsed.same_site(), Some(SameSite::Strict));
        assert_eq!(parsed.secure(), Some(true));
        assert_eq!(parsed.max_age(), Some(cookie::time::Duration::seconds(60)));
        assert!(set.starts_with("nelcota_admin=tok"), "{set}");

        // Plain HTTP (local dev): no Secure, or the browser would drop it.
        let plain = session_cookie("tok".into(), cookie::time::Duration::seconds(60), false);
        assert!(!plain.contains("Secure"), "{plain}");

        let cleared = Cookie::parse(session_cookie(
            String::new(),
            cookie::time::Duration::ZERO,
            false,
        ))
        .unwrap();
        assert_eq!(cleared.value(), "");
        assert_eq!(cleared.max_age(), Some(cookie::time::Duration::ZERO));
    }
}
