//! Migrations from the panel (migration V6).
//!
//! The panel applies DDL straight to the database, but deploys trust
//! `migrations/`. Each panel DDL lands in `nelcota.panel_changes`; "Generate
//! migration" bundles the pending ones into a `V<n>__<name>.sql` and records it
//! in `nelcota.user_migrations` exactly as `nelcota migrate` would (same
//! refinery checksum). Whoever commits the file into `migrations/` runs
//! nothing twice; whoever edits it is stopped by `migrate`.

use std::{
    collections::BTreeMap,
    path::{Path as FsPath, PathBuf},
};

use axum::{
    Json,
    extract::{Path, State},
    http::header,
    response::{IntoResponse, Response},
};
use serde::Deserialize;
use serde_json::{Value, json};

use crate::{AdminState, ApiError};

/// Table used by `nelcota migrate` (crates/cli/src/db.rs).
const USER_MIGRATIONS: &str = "nelcota.user_migrations";

/// DDL refinery uses for its control table: created here when the project
/// has never run `migrate`.
const CREATE_USER_MIGRATIONS: &str = "CREATE TABLE IF NOT EXISTS nelcota.user_migrations(
             version INT4 PRIMARY KEY,
             name VARCHAR(255),
             applied_on VARCHAR(255),
             checksum VARCHAR(255))";

/// `V12__create_orders.sql` → `(12, "create_orders")`.
pub fn parse_filename(filename: &str) -> Option<(i32, String)> {
    let stem = filename.strip_suffix(".sql")?;
    let (version, name) = stem.strip_prefix('V')?.split_once("__")?;
    let version = version.parse().ok().filter(|v| *v > 0)?;
    Some((version, name.to_owned()))
}

/// Migration files in the project folder (empty if it does not exist).
fn folder_migrations(dir: Option<&FsPath>) -> BTreeMap<i32, String> {
    let Some(Ok(entries)) = dir.map(std::fs::read_dir) else {
        return BTreeMap::new();
    };
    entries
        .filter_map(|e| e.ok()?.file_name().into_string().ok())
        .filter_map(|name| parse_filename(&name))
        .collect()
}

/// Generated file name: lowercase, digits and `_`, like the other migrations.
fn valid_name(name: &str) -> bool {
    (1..=60).contains(&name.len())
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        && !name.starts_with('_')
}

/// Next free version: above everything in the database, in the folder or
/// among panel-generated ones (an unapplied file also takes its number).
pub fn next_version(taken: impl IntoIterator<Item = i32>) -> i32 {
    taken.into_iter().max().unwrap_or(0) + 1
}

/// File text. Each change becomes a block with the panel's message as a
/// comment; statements end in `;` so they run as a single batch.
pub fn render(generated_at: &str, changes: &[(String, String, Vec<String>)]) -> String {
    let mut sql = format!(
        "-- Generated by the Nelcota panel at {generated_at}.\n\
         -- Already recorded as applied in the database where it was generated:\n\
         -- put this file in migrations/ and commit it. Do not edit it (the\n\
         -- checksum would change and `nelcota migrate` would refuse it).\n"
    );
    for (applied_at, summary, statements) in changes {
        sql.push_str(&format!("\n-- {summary} ({applied_at})\n"));
        for statement in statements {
            let statement = statement.trim().trim_end_matches(';');
            sql.push_str(statement);
            sql.push_str(";\n");
        }
    }
    sql
}

/// Applied versions (`user_migrations` may not exist yet).
async fn applied(
    client: &tokio_postgres::Client,
) -> Result<BTreeMap<i32, (String, String)>, ApiError> {
    let exists: bool = client
        .query_one("SELECT to_regclass($1) IS NOT NULL", &[&USER_MIGRATIONS])
        .await?
        .get(0);
    if !exists {
        return Ok(BTreeMap::new());
    }
    let rows = client
        .query(
            "SELECT version, coalesce(name, ''), coalesce(applied_on, '') FROM nelcota.user_migrations",
            &[],
        )
        .await?;
    Ok(rows
        .iter()
        .map(|r| (r.get(0), (r.get(1), r.get(2))))
        .collect())
}

async fn exported(client: &tokio_postgres::Client) -> Result<BTreeMap<i32, String>, ApiError> {
    let rows = client
        .query(
            "SELECT version, filename FROM nelcota.panel_migrations",
            &[],
        )
        .await?;
    Ok(rows.iter().map(|r| (r.get(0), r.get(1))).collect())
}

/// `GET /admin/api/migrations`
pub async fn list(
    State(state): State<AdminState>,
) -> Result<Json<crate::contracts::MigrationsData>, ApiError> {
    let client = state.db.get().await?;
    let applied = applied(&client).await?;
    let exported = exported(&client).await?;
    let dir = state.migrations_dir.as_deref();
    let folder = folder_migrations(dir);

    let versions: std::collections::BTreeSet<i32> = applied
        .keys()
        .chain(folder.keys())
        .chain(exported.keys())
        .copied()
        .collect();
    let migrations: Vec<Value> = versions
        .iter()
        .rev()
        .map(|v| {
            let name = applied
                .get(v)
                .map(|(n, _)| n.clone())
                .or_else(|| folder.get(v).cloned())
                .or_else(|| {
                    exported
                        .get(v)
                        .and_then(|f| parse_filename(f))
                        .map(|(_, n)| n)
                })
                .unwrap_or_default();
            json!({
                "version": v,
                "name": name,
                "applied_on": applied.get(v).map(|(_, at)| at),
                // `null` when the folder is not reachable from the server.
                "in_folder": dir.map(|_| folder.contains_key(v)),
                "from_panel": exported.contains_key(v),
            })
        })
        .collect();

    let pending: Vec<Value> = client
        .query(
            "SELECT id, to_char(applied_at, 'YYYY-MM-DD\"T\"HH24:MI:SSTZH:TZM'), summary, statements,
                    kind, target
               FROM nelcota.panel_changes WHERE exported_in IS NULL ORDER BY id",
            &[],
        )
        .await?
        .iter()
        .map(|r| {
            json!({
                "id": r.get::<_, i64>(0),
                "applied_at": r.get::<_, String>(1),
                "summary": r.get::<_, String>(2),
                "statements": r.get::<_, Vec<String>>(3),
                // The panel describes the change in its own language from these;
                // `summary` (English, or the old Portuguese) is the fallback.
                "kind": r.get::<_, Option<String>>(4),
                "target": r.get::<_, Option<String>>(5),
            })
        })
        .collect();

    crate::contracts::response::<crate::contracts::MigrationsData>(json!({
        "migrations": migrations,
        "pending": pending,
        "next_version": next_version(versions.iter().copied()),
        "folder": dir.map(|d| d.display().to_string()),
    }))
}

#[derive(Deserialize)]
pub struct ExportRequest {
    name: String,
}

/// `POST /admin/api/migrations` `{name}`: generates the migration with the
/// pending changes and records it as applied in this database.
pub async fn export(
    State(state): State<AdminState>,
    Json(body): Json<ExportRequest>,
) -> Result<Json<crate::contracts::ExportedMigration>, ApiError> {
    let name = body.name.trim();
    if !valid_name(name) {
        return Err(ApiError::bad_request(
            "invalid_migration_name",
            "name with lowercase letters, digits and _ (up to 60), e.g. create_orders",
        ));
    }
    let mut client = state.db.get().await?;
    let tx = client.transaction().await?;
    // One generation at a time: two tabs never compete for the same number.
    tx.batch_execute("LOCK TABLE nelcota.panel_changes IN SHARE ROW EXCLUSIVE MODE")
        .await?;
    let rows = tx
        .query(
            "SELECT id, to_char(applied_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI \"UTC\"'),
                    summary, statements
               FROM nelcota.panel_changes WHERE exported_in IS NULL ORDER BY id",
            &[],
        )
        .await?;
    if rows.is_empty() {
        return Err(ApiError::conflict(
            "no_pending_changes",
            "no panel changes outside migrations",
        ));
    }
    let ids: Vec<i64> = rows.iter().map(|r| r.get(0)).collect();
    let changes: Vec<(String, String, Vec<String>)> = rows
        .iter()
        .map(|r| (r.get(1), r.get(2), r.get(3)))
        .collect();

    tx.batch_execute(CREATE_USER_MIGRATIONS).await?;
    let taken: Vec<i32> = tx
        .query(
            "SELECT version FROM nelcota.user_migrations
             UNION SELECT version FROM nelcota.panel_migrations",
            &[],
        )
        .await?
        .iter()
        .map(|r| r.get(0))
        .chain(folder_migrations(state.migrations_dir.as_deref()).into_keys())
        .collect();
    let version = next_version(taken);

    let (generated_at, applied_on): (String, String) = {
        let row = tx
            .query_one(
                "SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI \"UTC\"'),
                        to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"')",
                &[],
            )
            .await?;
        (row.get(0), row.get(1))
    };
    let sql = render(&generated_at, &changes);
    let stem = format!("V{version}__{name}");
    let filename = format!("{stem}.sql");
    // The same computation `migrate` does when it reads the file.
    let checksum = refinery::Migration::unapplied(&stem, &sql)
        .map_err(|e| ApiError::from(format!("invalid migration: {e}")))?
        .checksum()
        .to_string();

    tx.execute(
        "INSERT INTO nelcota.user_migrations (version, name, applied_on, checksum)
         VALUES ($1, $2, $3, $4)",
        &[&version, &name, &applied_on, &checksum],
    )
    .await?;
    tx.execute(
        "INSERT INTO nelcota.panel_migrations (version, filename, sql) VALUES ($1, $2, $3)",
        &[&version, &filename, &sql],
    )
    .await?;
    tx.execute(
        "UPDATE nelcota.panel_changes SET exported_in = $1 WHERE id = ANY($2)",
        &[&version, &ids],
    )
    .await?;
    tx.commit().await?;
    tracing::info!(
        version,
        changes = ids.len(),
        "migration generated by the panel"
    );
    crate::contracts::response::<crate::contracts::ExportedMigration>(json!({
        "version": version,
        "filename": filename,
        "sql": sql,
        "message": format!("{filename} generated with {} change(s)", ids.len()),
    }))
}

/// `GET /admin/api/migrations/{version}/file`: the generated file, unchanged.
pub async fn file(
    State(state): State<AdminState>,
    Path(version): Path<i32>,
) -> Result<Response, ApiError> {
    let client = state.db.get().await?;
    let row = client
        .query_opt(
            "SELECT filename, sql FROM nelcota.panel_migrations WHERE version = $1",
            &[&version],
        )
        .await?
        .ok_or_else(|| {
            ApiError::not_found(
                "migration_not_from_panel",
                "migration was not generated by the panel",
            )
        })?;
    let filename: String = row.get(0);
    let sql: String = row.get(1);
    Ok((
        [
            (
                header::CONTENT_TYPE,
                "application/sql; charset=utf-8".to_owned(),
            ),
            (
                header::CONTENT_DISPOSITION,
                format!("attachment; filename=\"{filename}\""),
            ),
        ],
        sql,
    )
        .into_response())
}

/// The project's migrations folder: the configured one or, inside the
/// project container, `/migrations` (the compose file mounts it read-only).
pub fn default_dir(configured: Option<PathBuf>) -> Option<PathBuf> {
    configured.or_else(|| {
        let mounted = PathBuf::from("/migrations");
        mounted.is_dir().then_some(mounted)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_file_names() {
        assert_eq!(
            parse_filename("V12__create_orders.sql"),
            Some((12, "create_orders".into()))
        );
        assert_eq!(parse_filename("V1__a.sql"), Some((1, "a".into())));
        for bad in [
            "V0__x.sql",
            "V1_x.sql",
            "1__x.sql",
            "V1__x.txt",
            "Vx__y.sql",
            "README.md",
        ] {
            assert_eq!(parse_filename(bad), None, "{bad}");
        }
    }

    #[test]
    fn next_version_goes_past_everything_that_exists() {
        assert_eq!(next_version([]), 1);
        // Database at V3, folder with an unapplied V5: the generated one is V6.
        assert_eq!(next_version([1, 2, 3, 5]), 6);
    }

    #[test]
    fn file_name() {
        assert!(valid_name("create_orders"));
        assert!(valid_name("v2_indexes"));
        for bad in [
            "",
            "Create",
            "with space",
            "naïve",
            "_x",
            "a-b",
            &"a".repeat(61),
        ] {
            assert!(!valid_name(bad), "{bad}");
        }
    }

    #[test]
    fn file_ends_each_statement_with_a_semicolon() {
        let sql = render(
            "2026-10-07 12:00 UTC",
            &[(
                "2026-10-07 11:58 UTC".into(),
                "table 'orders' created".into(),
                vec![
                    "CREATE TABLE orders (id int)".into(),
                    "ALTER TABLE orders ENABLE ROW LEVEL SECURITY;".into(),
                ],
            )],
        );
        assert!(sql.starts_with("-- Generated by the Nelcota panel at 2026-10-07 12:00 UTC."));
        assert!(sql.contains("\n-- table 'orders' created (2026-10-07 11:58 UTC)\nCREATE TABLE orders (id int);\nALTER TABLE orders ENABLE ROW LEVEL SECURITY;\n"));
    }
}
