//! Dependencies shared by the panel workflows.
use crate::{Credentials, DeniedLog, HostLink, Sessions, SqlExecutor, TokenIssuer};
use deadpool_postgres::Pool;
use nelcota_api::CatalogHandle;
use nelcota_auth::RateLimiter;
use std::sync::Arc;
#[derive(Clone)]
pub struct AdminState {
    /// Bounded SQL executions shared by all panel sessions.
    pub sql: Arc<SqlExecutor>,
    /// Admin pool (role that owns the schema).
    pub db: Pool,
    /// Admin config, for the SQL editor's dedicated connections.
    pub db_config: tokio_postgres::Config,
    pub catalog: Arc<CatalogHandle>,
    pub credentials: Arc<Credentials>,
    pub sessions: Arc<Sessions>,
    pub limiter: Arc<RateLimiter>,
    /// Cookie with `Secure` (behind Caddy/HTTPS).
    pub secure_cookies: bool,
    /// Current project, the host's project list and single sign-on.
    pub host: Arc<HostLink>,
    /// service_role token issuing from the API page.
    pub tokens: Arc<TokenIssuer>,
    /// The project's `migrations/` folder, when reachable (so migrations
    /// generated by the panel never collide with unapplied files).
    pub migrations_dir: Option<std::path::PathBuf>,
    /// File storage, when a backend is configured.
    pub storage: Option<nelcota_storage::StorageState>,
    /// How the app's users can sign in (from the environment, read-only).
    pub sign_in: Arc<crate::contracts::SignIn>,
    /// API requests refused recently; the server records into it.
    pub denied: Arc<DeniedLog>,
}
