//! PITR settings, private files and Docker/systemd preparation.
use crate::{
    envfile::{EnvFile, write_private},
    host::{Host, Runtime},
    native,
    project::{Project, run},
    util::{self, ok, step},
};
use anyhow::{Context, bail};
use std::{fs, process::Command};

/// pgBackRest settings of the project (S3 keys included).
pub const ENV_FILE: &str = "pgbackrest.env";
pub const DOCKERFILE: &str = include_str!("../../../../deploy/postgres/Dockerfile");
/// How a compose file from before PITR becomes the current template, as
/// `(old, new)` text that must each appear exactly once: Postgres is built
/// from `postgres/Dockerfile`, reads `pgbackrest.env` when PITR is on, and
/// joins an `egress` network of its own to reach S3 (the `internal` network
/// has no way out; nothing can connect in through either).
pub const COMPOSE_UPGRADE: [(&str, &str); 3] = [
    (
        "    image: postgres:17-alpine\n",
        "    # postgres:17-alpine plus pgBackRest (point-in-time recovery: `nelcota pitr`).\n    build: ./postgres\n    env_file:\n      - path: pgbackrest.env\n        required: false\n",
    ),
    (
        "    networks: [internal]\n",
        "    # egress: outbound only, for archiving WAL to S3.\n    networks: [internal, egress]\n",
    ),
    (
        "networks:\n  internal:\n    internal: true\n",
        "networks:\n  internal:\n    internal: true\n  egress: {}\n",
    ),
];
const RETENTION_FULL: u32 = 2;
pub fn enabled(project: &Project) -> bool {
    project.path(ENV_FILE).is_file()
}

/// Writes `postgres/Dockerfile` into a project folder.
pub fn write_dockerfile(project: &Project) -> anyhow::Result<()> {
    let dir = project.path("postgres");
    fs::create_dir_all(&dir)?;
    fs::write(dir.join("Dockerfile"), DOCKERFILE)?;
    Ok(())
}

/// `pgbackrest.env` for a project, from the host's S3 settings. The
/// repository is `<bucket>/<project>/pitr`, beside the dumps' `<project>/`.
fn render_env(project: &str, pg_data: &str, host: &EnvFile) -> anyhow::Result<String> {
    let get = |key: &str| -> anyhow::Result<String> {
        host.get(key)?.with_context(|| {
            format!("{key} is not set in host.env: PITR needs S3-compatible storage (see docs/backup.md)")
        })
    };
    let endpoint = get("NELCOTA_BACKUP_S3_ENDPOINT")?;
    let (endpoint_host, port) = split_endpoint(&endpoint)?;
    let region = host
        .get("NELCOTA_BACKUP_S3_REGION")?
        .unwrap_or_else(|| "us-east-1".into());
    let uri_style = host
        .get("NELCOTA_BACKUP_S3_URI_STYLE")?
        .unwrap_or_else(|| "host".into());
    if !matches!(uri_style.as_str(), "host" | "path") {
        bail!("NELCOTA_BACKUP_S3_URI_STYLE must be host or path, not '{uri_style}'");
    }
    let mut env = format!(
        "# pgBackRest for project \"{project}\". Generated by `nelcota pitr enable` at {now}.\n\
         # CONTAINS SECRETS (S3 keys): mode 600. Regenerate after changing host.env.\n\
         PGBACKREST_REPO1_TYPE=s3\n\
         PGBACKREST_REPO1_PATH=/{project}/pitr\n\
         PGBACKREST_REPO1_S3_ENDPOINT={endpoint_host}\n\
         PGBACKREST_REPO1_S3_BUCKET={bucket}\n\
         PGBACKREST_REPO1_S3_REGION={region}\n\
         PGBACKREST_REPO1_S3_URI_STYLE={uri_style}\n\
         PGBACKREST_REPO1_S3_KEY={key}\n\
         PGBACKREST_REPO1_S3_KEY_SECRET={secret}\n\
         PGBACKREST_REPO1_RETENTION_FULL={RETENTION_FULL}\n\
         PGBACKREST_PG1_PATH={pg_data}\n\
         PGBACKREST_START_FAST=y\n\
         PGBACKREST_LOG_LEVEL_CONSOLE=warn\n\
         PGBACKREST_LOG_LEVEL_FILE=off\n",
        now = util::timestamp(),
        bucket = get("NELCOTA_BACKUP_S3_BUCKET")?,
        key = get("NELCOTA_BACKUP_S3_ACCESS_KEY")?,
        secret = get("NELCOTA_BACKUP_S3_SECRET_KEY")?,
    );
    if let Some(port) = port {
        env.push_str(&format!("PGBACKREST_REPO1_STORAGE_PORT={port}\n"));
    }
    // Only for storage with a self-signed certificate (a MinIO of your own).
    if host.get("NELCOTA_BACKUP_S3_VERIFY_TLS")?.as_deref() == Some("false") {
        env.push_str("PGBACKREST_REPO1_STORAGE_VERIFY_TLS=n\n");
    }
    Ok(env)
}

/// The same settings as a `pgbackrest.conf`: `PGBACKREST_REPO1_S3_KEY=x`
/// becomes `repo1-s3-key=x`, the Postgres path goes to the stanza.
fn render_conf(env: &str) -> String {
    let mut global = String::from("[global]\n");
    let mut stanza = String::from("\n[main]\n");
    for line in env.lines() {
        let Some((key, value)) = line
            .strip_prefix("PGBACKREST_")
            .and_then(|l| l.split_once('='))
        else {
            continue;
        };
        let option = key.to_lowercase().replace('_', "-");
        let section = if option.starts_with("pg1-") {
            &mut stanza
        } else {
            &mut global
        };
        section.push_str(&format!("{option}={value}\n"));
    }
    format!(
        "# Generated by `nelcota pitr enable` from pgbackrest.env. CONTAINS SECRETS.\n{global}{stanza}"
    )
}

/// `https://s3.example.com:9000/` → (`s3.example.com`, Some(9000)).
/// pgBackRest always speaks HTTPS to S3.
fn split_endpoint(endpoint: &str) -> anyhow::Result<(String, Option<u16>)> {
    if endpoint.starts_with("http://") {
        bail!("pgBackRest only talks to S3 over HTTPS: NELCOTA_BACKUP_S3_ENDPOINT is {endpoint}");
    }
    let rest = endpoint.strip_prefix("https://").unwrap_or(endpoint);
    let authority = rest.split('/').next().unwrap_or_default();
    match authority.rsplit_once(':') {
        Some((host, port)) => {
            let port = port.parse().with_context(|| {
                format!("invalid port in NELCOTA_BACKUP_S3_ENDPOINT: {endpoint}")
            })?;
            Ok((host.to_owned(), Some(port)))
        }
        None if !authority.is_empty() => Ok((authority.to_owned(), None)),
        None => bail!("invalid NELCOTA_BACKUP_S3_ENDPOINT: {endpoint}"),
    }
}

/// Brings a compose file from before PITR to the current template (see
/// [`COMPOSE_UPGRADE`]). `false` when it was edited beyond recognition.
fn upgrade_compose(project: &Project) -> anyhow::Result<bool> {
    let path = project.path("docker-compose.yml");
    let mut compose = fs::read_to_string(&path)?;
    if COMPOSE_UPGRADE.iter().all(|(_, new)| compose.contains(new)) {
        return Ok(true);
    }
    if COMPOSE_UPGRADE
        .iter()
        .any(|(old, _)| compose.matches(old).count() != 1)
    {
        return Ok(false);
    }
    for (old, new) in COMPOSE_UPGRADE {
        compose = compose.replace(old, new);
    }
    fs::write(&path, compose)?;
    ok("docker-compose.yml: Postgres built with pgBackRest, with an egress network");
    Ok(true)
}

pub(super) fn prepare(host: &Host, project: &Project) -> anyhow::Result<()> {
    let pg_data = match project.runtime {
        Runtime::Docker => "/var/lib/postgresql/data",
        Runtime::Systemd => native::PG_DATA,
    };
    let env = render_env(&project.name, pg_data, &host.secrets())?;
    step(&format!(
        "Enabling point-in-time recovery for {}",
        project.name
    ));
    match project.runtime {
        Runtime::Docker => {
            write_dockerfile(project)?;
            if !upgrade_compose(project)? {
                let changes: Vec<String> = COMPOSE_UPGRADE
                    .iter()
                    .map(|(old, new)| format!("replace:\n{old}with:\n{new}"))
                    .collect();
                bail!(
                    "{} was edited and could not be updated; make these changes and run this again:\n\n{}",
                    project.path("docker-compose.yml").display(),
                    changes.join("\n")
                );
            }
            write_private(&project.path(ENV_FILE), &env)?;
            step("Rebuilding Postgres with pgBackRest");
            project.compose_ok(&["up", "-d", "--build", "postgres"])?;
        }
        Runtime::Systemd => {
            write_private(&project.path(ENV_FILE), &env)?;
            fs::create_dir_all("/etc/pgbackrest")?;
            write_private(native::PGBACKREST_CONF.as_ref(), &render_conf(&env))?;
            run(
                Command::new("chown").args(["postgres:postgres", native::PGBACKREST_CONF]),
                "chown of pgbackrest.conf",
            )?;
        }
    }
    Ok(())
}
pub(super) fn remove(project: &Project) -> anyhow::Result<()> {
    fs::remove_file(project.path(ENV_FILE))?;
    if project.runtime == Runtime::Systemd {
        let _ = fs::remove_file(native::PGBACKREST_CONF);
    }
    Ok(())
}
#[cfg(test)]
mod tests {
    use super::*;

    fn host_env(name: &str, content: &str) -> EnvFile {
        let path =
            std::env::temp_dir().join(format!("nelcota-pitr-{name}-{}.env", std::process::id()));
        fs::write(&path, content).unwrap();
        EnvFile::new(path)
    }

    const S3: &str = "NELCOTA_BACKUP_S3_ENDPOINT=https://minio.internal:9000\n\
                      NELCOTA_BACKUP_S3_BUCKET=backups\n\
                      NELCOTA_BACKUP_S3_ACCESS_KEY=AK\n\
                      NELCOTA_BACKUP_S3_SECRET_KEY=SK\n";

    #[test]
    fn the_env_points_pgbackrest_at_the_projects_folder() {
        let env = render_env("shop", "/var/lib/postgresql/data", &host_env("full", S3)).unwrap();
        for line in [
            "PGBACKREST_REPO1_PATH=/shop/pitr",
            "PGBACKREST_REPO1_S3_ENDPOINT=minio.internal",
            "PGBACKREST_REPO1_STORAGE_PORT=9000",
            "PGBACKREST_REPO1_S3_BUCKET=backups",
            "PGBACKREST_REPO1_S3_REGION=us-east-1",
            "PGBACKREST_REPO1_S3_URI_STYLE=host",
            "PGBACKREST_REPO1_S3_KEY=AK",
            "PGBACKREST_REPO1_S3_KEY_SECRET=SK",
        ] {
            assert!(env.lines().any(|l| l == line), "{line} missing:\n{env}");
        }
        assert!(!env.contains("VERIFY_TLS"));

        let own_minio =
            format!("{S3}NELCOTA_BACKUP_S3_VERIFY_TLS=false\nNELCOTA_BACKUP_S3_URI_STYLE=path\n");
        let env = render_env("shop", "/data", &host_env("minio", &own_minio)).unwrap();
        assert!(env.contains("PGBACKREST_REPO1_STORAGE_VERIFY_TLS=n\n"));
        assert!(env.contains("PGBACKREST_REPO1_S3_URI_STYLE=path\n"));

        assert!(render_env("shop", "/data", &host_env("none", "")).is_err());
        let bad_style = format!("{S3}NELCOTA_BACKUP_S3_URI_STYLE=virtual\n");
        assert!(render_env("shop", "/data", &host_env("style", &bad_style)).is_err());
    }

    #[test]
    fn old_compose_files_upgrade_to_the_template() {
        let current = crate::scaffold::render_compose("shop", "1gb");
        let mut old = current.clone();
        for (before, after) in COMPOSE_UPGRADE {
            assert_eq!(current.matches(after).count(), 1, "{after}");
            old = old.replace(after, before);
        }
        let dir = std::env::temp_dir().join(format!("nelcota-pitr-compose-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let file = dir.join("docker-compose.yml");
        fs::write(&file, &old).unwrap();
        let project = Project::new("shop", &dir, Runtime::Docker);
        assert!(upgrade_compose(&project).unwrap());
        assert_eq!(fs::read_to_string(&file).unwrap(), current);
        // Idempotent; an edited file is left alone.
        assert!(upgrade_compose(&project).unwrap());
        assert_eq!(fs::read_to_string(&file).unwrap(), current);
        fs::write(
            &file,
            "services: {}
",
        )
        .unwrap();
        assert!(!upgrade_compose(&project).unwrap());
    }

    #[test]
    fn the_conf_file_holds_the_same_settings() {
        let env = render_env("shop", native::PG_DATA, &host_env("conf", S3)).unwrap();
        let conf = render_conf(&env);
        let (global, stanza) = conf.split_once("\n[main]\n").unwrap();
        assert!(global.contains("[global]\nrepo1-type=s3\n"), "{conf}");
        assert!(global.contains("\nrepo1-s3-key-secret=SK\n"));
        assert!(global.contains("\nrepo1-storage-port=9000\n"));
        assert!(global.contains("\nstart-fast=y\n"));
        assert_eq!(stanza, "pg1-path=/var/lib/postgresql/17/main\n");
    }

    #[test]
    fn endpoints_split_into_host_and_port() {
        assert_eq!(
            split_endpoint("https://s3.us-west-002.backblazeb2.com").unwrap(),
            ("s3.us-west-002.backblazeb2.com".to_owned(), None)
        );
        assert_eq!(
            split_endpoint("https://minio.internal:9000/").unwrap(),
            ("minio.internal".to_owned(), Some(9000))
        );
        assert!(split_endpoint("http://minio:9000").is_err());
        assert!(split_endpoint("https://").is_err());
        assert!(split_endpoint("https://x:port").is_err());
    }
}
