//! Configuration from environment variables (`NELCOTA_*`) and, optionally, a
//! TOML file (`nelcota.toml` or the path in `NELCOTA_CONFIG`). Environment
//! variables take precedence over the file.

use std::{fmt, net::SocketAddr, str::FromStr};

use figment::{
    Figment,
    providers::{Env, Format, Serialized, Toml},
};
use serde::{Deserialize, Serialize};

/// Sensitive value: never shows in `Debug` (and therefore never reaches a log).
#[derive(Clone, Default, Deserialize, Serialize)]
#[serde(transparent)]
pub struct Secret(String);

impl Secret {
    pub fn new(value: impl Into<String>) -> Self {
        Secret(value.into())
    }

    pub fn expose(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for Secret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Secret(***)")
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum LogFormat {
    #[default]
    Text,
    Json,
}

/// Where storage keeps the bytes (D77).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum StorageBackend {
    /// No storage routes.
    #[default]
    Off,
    /// A local directory (`NELCOTA_STORAGE_DIR`).
    Disk,
    /// An S3-compatible bucket (`NELCOTA_STORAGE_S3_*`).
    S3,
}

/// Default REST body limit: axum's own default, which the API always had.
/// A body is buffered and parsed whole, and a 1000-row insert of typical
/// rows fits well under it; raise it for larger batches if memory allows.
pub const DEFAULT_MAX_BODY_BYTES: usize = 2 * 1024 * 1024;

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Config {
    /// Postgres URL with a role that owns the schema (used only for migrations
    /// and to set the `authenticator` role password). The API connects to the
    /// same host/database, but as `authenticator`.
    pub database_url: Secret,
    /// Password of the `authenticator` role.
    pub authenticator_password: Secret,
    /// Ed25519 private key (PKCS#8, as PEM or one-line base64) used to sign the
    /// JWTs (EdDSA). The public key is published in the JWKS.
    pub jwt_private_key: Option<Secret>,
    /// HS256 secret (simple/legacy mode). With an EdDSA key it is only used to
    /// VERIFY old tokens; otherwise it also signs.
    pub jwt_secret: Option<Secret>,
    /// `iss` claim of issued tokens.
    pub jwt_issuer: String,
    /// Lifetime of the access JWT, in seconds.
    pub jwt_expiry_secs: u64,
    /// Lifetime of the refresh token (renewed on each rotation), in days.
    pub refresh_token_ttl_days: u32,
    pub signup_enabled: bool,
    /// Requests per minute, per IP, on the login/signup endpoints.
    pub auth_rate_limit_per_minute: u32,
    /// Trust `X-Forwarded-For` (only behind a proxy such as Caddy).
    pub trust_proxy: bool,
    /// SMTP for auth emails, as `smtps://user:password@host:465` (or
    /// `smtp://...:587?tls=required`). Without it, password recovery is off.
    pub smtp_url: Option<Secret>,
    /// Sender of the emails: `Shop <no-reply@shop.com>`.
    pub smtp_from: Option<String>,
    /// App page that receives the password recovery link. The token goes in the
    /// fragment (`#type=recovery&token=...`), which never reaches a server.
    pub password_recovery_url: Option<String>,
    /// App page that receives the signup confirmation link. Setting it makes
    /// signup wait for the email to be confirmed before password sign-in.
    pub email_confirmation_url: Option<String>,
    /// App page that receives the magic link (passwordless sign-in). Without
    /// it, `/auth/v1/magiclink` is off.
    pub magic_link_url: Option<String>,
    /// Public origin of this API (`https://api.shop.com`): sign-in providers
    /// send people back to `<api_url>/auth/v1/callback`.
    pub api_url: Option<String>,
    /// App pages a provider sign-in may return to, comma separated. A
    /// `redirect_to` must sit under one of them (same origin, path below).
    pub oauth_redirect_urls: Option<String>,
    pub oauth_google_client_id: Option<String>,
    pub oauth_google_client_secret: Option<Secret>,
    pub oauth_github_client_id: Option<String>,
    pub oauth_github_client_secret: Option<Secret>,
    /// Panel login (separate from end users). Without both, the panel is off.
    pub admin_email: Option<String>,
    /// PHC argon2id hash of the admin password (generated by `nelcota init`).
    pub admin_password_hash: Option<Secret>,
    /// Secret shared by the projects of one host for the panel's single sign-on
    /// (SSO handoff). Absent = per-project login.
    pub admin_sso_secret: Option<Secret>,
    /// Name of this project on the host (`nelcota init --project`).
    pub project_name: Option<String>,
    /// Public list of the host's projects (name + URL), for the panel switcher.
    pub host_registry: Option<std::path::PathBuf>,
    /// The project's `migrations/` folder, read by the panel when generating
    /// migrations. In the project container, `/migrations` is detected on its own.
    pub migrations_dir: Option<std::path::PathBuf>,
    /// Schema exposed by the REST API.
    pub db_schema: String,
    /// Row cap per API collection (`None` uses 1000).
    pub max_rows: Option<i64>,
    /// Largest REST request body (`/rest/v1`), in bytes.
    pub max_body_bytes: usize,
    pub listen: SocketAddr,
    pub db_pool_size: usize,
    pub request_timeout_secs: u64,
    /// `statement_timeout` of the API connections.
    pub statement_timeout_secs: u64,
    pub log_format: LogFormat,
    /// File storage: `off`, `disk` or `s3`.
    pub storage_backend: StorageBackend,
    /// Directory of the disk backend.
    pub storage_dir: Option<std::path::PathBuf>,
    /// S3 endpoint (`https://<account>.r2.cloudflarestorage.com`); empty = AWS.
    pub storage_s3_endpoint: Option<String>,
    pub storage_s3_bucket: Option<String>,
    pub storage_s3_region: String,
    pub storage_s3_access_key_id: Option<String>,
    pub storage_s3_secret_access_key: Option<Secret>,
    /// `bucket.endpoint` URLs instead of `endpoint/bucket`.
    pub storage_s3_virtual_hosted: bool,
    /// Largest file accepted, in bytes (a bucket can only lower it).
    pub storage_max_file_size: u64,
    /// Cap on the bytes of all buckets together (`None` = no cap).
    pub storage_max_total_size: Option<u64>,
    /// Disk backend: refuse an upload that would leave less free space.
    pub storage_min_free_bytes: u64,
    /// Origin of public file URLs (e.g. `https://files.shop.com`); `None` =
    /// the API's own.
    pub storage_public_url: Option<String>,
    /// Longest an upload may take, in seconds.
    pub storage_upload_timeout_secs: u64,
}

#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error(transparent)]
    Load(#[from] Box<figment::Error>),
    #[error("{0}")]
    Invalid(&'static str),
    #[error("invalid NELCOTA_DATABASE_URL: {0}")]
    DatabaseUrl(tokio_postgres::Error),
}

impl Default for Config {
    fn default() -> Self {
        Config {
            database_url: Secret::default(),
            authenticator_password: Secret::default(),
            jwt_private_key: None,
            jwt_secret: None,
            jwt_issuer: "nelcota".into(),
            jwt_expiry_secs: 900,
            refresh_token_ttl_days: 30,
            signup_enabled: true,
            auth_rate_limit_per_minute: 30,
            trust_proxy: false,
            smtp_url: None,
            smtp_from: None,
            password_recovery_url: None,
            email_confirmation_url: None,
            magic_link_url: None,
            api_url: None,
            oauth_redirect_urls: None,
            oauth_google_client_id: None,
            oauth_google_client_secret: None,
            oauth_github_client_id: None,
            oauth_github_client_secret: None,
            admin_email: None,
            admin_password_hash: None,
            admin_sso_secret: None,
            project_name: None,
            host_registry: None,
            migrations_dir: None,
            db_schema: "public".into(),
            max_rows: Some(1000),
            max_body_bytes: DEFAULT_MAX_BODY_BYTES,
            listen: SocketAddr::from(([0, 0, 0, 0], 8000)),
            db_pool_size: 10,
            request_timeout_secs: 15,
            statement_timeout_secs: 10,
            log_format: LogFormat::Text,
            storage_backend: StorageBackend::Off,
            storage_dir: None,
            storage_s3_endpoint: None,
            storage_s3_bucket: None,
            storage_s3_region: "auto".into(),
            storage_s3_access_key_id: None,
            storage_s3_secret_access_key: None,
            storage_s3_virtual_hosted: false,
            storage_max_file_size: 50 * 1024 * 1024,
            storage_max_total_size: None,
            storage_min_free_bytes: 1024 * 1024 * 1024,
            storage_public_url: None,
            storage_upload_timeout_secs: 3600,
        }
    }
}

impl Config {
    pub fn load() -> Result<Self, ConfigError> {
        let file = std::env::var("NELCOTA_CONFIG").unwrap_or_else(|_| "nelcota.toml".into());
        let config: Config = Figment::from(Serialized::defaults(Config::default()))
            .merge(Toml::file(file))
            .merge(Env::prefixed("NELCOTA_").ignore(&["config"]))
            .extract()
            .map_err(Box::new)?;
        config.validate()?;
        Ok(config)
    }

    pub fn validate(&self) -> Result<(), ConfigError> {
        if self.database_url.expose().is_empty() {
            return Err(ConfigError::Invalid("NELCOTA_DATABASE_URL is required"));
        }
        if self.authenticator_password.expose().len() < 16 {
            return Err(ConfigError::Invalid(
                "NELCOTA_AUTHENTICATOR_PASSWORD needs at least 16 characters",
            ));
        }
        match (self.jwt_private_key(), self.jwt_secret()) {
            (None, None) => {
                return Err(ConfigError::Invalid(
                    "set NELCOTA_JWT_PRIVATE_KEY (recommended) or NELCOTA_JWT_SECRET",
                ));
            }
            (_, Some(secret)) if secret.len() < 32 => {
                return Err(ConfigError::Invalid(
                    "NELCOTA_JWT_SECRET needs at least 32 characters",
                ));
            }
            _ => {}
        }
        if self.jwt_expiry_secs == 0 || self.refresh_token_ttl_days == 0 {
            return Err(ConfigError::Invalid(
                "NELCOTA_JWT_EXPIRY_SECS and NELCOTA_REFRESH_TOKEN_TTL_DAYS must be > 0",
            ));
        }
        if self.db_pool_size == 0 {
            return Err(ConfigError::Invalid("NELCOTA_DB_POOL_SIZE must be > 0"));
        }
        if self.max_rows.is_some_and(|rows| rows <= 0) {
            return Err(ConfigError::Invalid("NELCOTA_MAX_ROWS must be > 0"));
        }
        if self.max_body_bytes == 0 {
            return Err(ConfigError::Invalid("NELCOTA_MAX_BODY_BYTES must be > 0"));
        }
        if self.request_timeout_secs == 0 {
            return Err(ConfigError::Invalid(
                "NELCOTA_REQUEST_TIMEOUT_SECS must be > 0",
            ));
        }
        // The statement must time out first, so a slow query answers its own
        // 504 and its transaction ends, instead of the request being dropped
        // while Postgres keeps working (0 turns the statement timeout off).
        if self.statement_timeout_secs > 0
            && self.request_timeout_secs <= self.statement_timeout_secs
        {
            return Err(ConfigError::Invalid(
                "NELCOTA_REQUEST_TIMEOUT_SECS must be greater than NELCOTA_STATEMENT_TIMEOUT_SECS",
            ));
        }
        if self.auth_rate_limit_per_minute == 0 {
            return Err(ConfigError::Invalid(
                "NELCOTA_AUTH_RATE_LIMIT_PER_MINUTE must be > 0 (requests per minute per IP)",
            ));
        }
        self.mail()?;
        self.validate_storage()?;
        self.database_config()?;
        Ok(())
    }

    fn validate_storage(&self) -> Result<(), ConfigError> {
        let set = |value: &Option<String>| value.as_deref().is_some_and(|v| !v.trim().is_empty());
        match self.storage_backend {
            StorageBackend::Off => return Ok(()),
            StorageBackend::Disk if self.storage_dir.is_none() => {
                return Err(ConfigError::Invalid(
                    "NELCOTA_STORAGE_BACKEND=disk needs NELCOTA_STORAGE_DIR",
                ));
            }
            StorageBackend::S3
                if !set(&self.storage_s3_bucket)
                    || !set(&self.storage_s3_access_key_id)
                    || non_empty(&self.storage_s3_secret_access_key).is_none() =>
            {
                return Err(ConfigError::Invalid(
                    "NELCOTA_STORAGE_BACKEND=s3 needs NELCOTA_STORAGE_S3_BUCKET, \
                     NELCOTA_STORAGE_S3_ACCESS_KEY_ID and NELCOTA_STORAGE_S3_SECRET_ACCESS_KEY",
                ));
            }
            _ => {}
        }
        if self.storage_max_file_size == 0 || self.storage_upload_timeout_secs == 0 {
            return Err(ConfigError::Invalid(
                "NELCOTA_STORAGE_MAX_FILE_SIZE and NELCOTA_STORAGE_UPLOAD_TIMEOUT_SECS must be > 0",
            ));
        }
        if let Some(url) = self.storage_public_url.as_deref().map(str::trim)
            && !url.is_empty()
            && !(url.starts_with("https://") || url.starts_with("http://"))
        {
            return Err(ConfigError::Invalid(
                "NELCOTA_STORAGE_PUBLIC_URL must be an http(s) URL",
            ));
        }
        Ok(())
    }

    /// Configured EdDSA key (an empty variable counts as absent).
    pub fn jwt_private_key(&self) -> Option<&str> {
        non_empty(&self.jwt_private_key)
    }

    /// Configured HS256 secret (an empty variable counts as absent).
    pub fn jwt_secret(&self) -> Option<&str> {
        non_empty(&self.jwt_secret)
    }

    /// Auth email: `None` when not configured; an error when half configured
    /// (better to fail at startup than on the first "forgot my password").
    pub fn mail(&self) -> Result<Option<MailConfig<'_>>, ConfigError> {
        let url = non_empty(&self.smtp_url);
        let from = trimmed(&self.smtp_from);
        let recovery = trimmed(&self.password_recovery_url);
        let confirmation = trimmed(&self.email_confirmation_url);
        let magic_link = trimmed(&self.magic_link_url);
        let any_page = recovery.is_some() || confirmation.is_some() || magic_link.is_some();
        let (url, from) = match (url, from) {
            (None, None) if !any_page => return Ok(None),
            (Some(url), Some(from)) => (url, from),
            (None, None) => {
                return Err(ConfigError::Invalid(
                    "the email link pages need NELCOTA_SMTP_URL and NELCOTA_SMTP_FROM",
                ));
            }
            _ => {
                return Err(ConfigError::Invalid(
                    "set NELCOTA_SMTP_URL and NELCOTA_SMTP_FROM together (or neither)",
                ));
            }
        };
        let Some(recovery_url) = recovery else {
            return Err(ConfigError::Invalid(
                "with SMTP configured, set NELCOTA_PASSWORD_RECOVERY_URL (the app page that receives the link)",
            ));
        };
        Ok(Some(MailConfig {
            smtp_url: url,
            from,
            recovery_url: link_page(
                recovery_url,
                "NELCOTA_PASSWORD_RECOVERY_URL must be an http(s) URL without a fragment (#)",
            )?,
            confirmation_url: confirmation
                .map(|page| {
                    link_page(
                        page,
                        "NELCOTA_EMAIL_CONFIRMATION_URL must be an http(s) URL without a fragment (#)",
                    )
                })
                .transpose()?,
            magic_link_url: magic_link
                .map(|page| {
                    link_page(
                        page,
                        "NELCOTA_MAGIC_LINK_URL must be an http(s) URL without a fragment (#)",
                    )
                })
                .transpose()?,
        }))
    }

    /// Provider sign-in: `None` without providers; an error when a provider is
    /// half configured or the URLs around the flow are missing.
    pub fn oauth(&self) -> Result<Option<OAuthConfig<'_>>, ConfigError> {
        let google = client(
            &self.oauth_google_client_id,
            &self.oauth_google_client_secret,
            "set NELCOTA_OAUTH_GOOGLE_CLIENT_ID and NELCOTA_OAUTH_GOOGLE_CLIENT_SECRET together",
        )?;
        let github = client(
            &self.oauth_github_client_id,
            &self.oauth_github_client_secret,
            "set NELCOTA_OAUTH_GITHUB_CLIENT_ID and NELCOTA_OAUTH_GITHUB_CLIENT_SECRET together",
        )?;
        if google.is_none() && github.is_none() {
            return Ok(None);
        }
        let api_url = trimmed(&self.api_url)
            .filter(|url| url.starts_with("https://") || url.starts_with("http://"))
            .ok_or(ConfigError::Invalid(
                "sign-in providers need NELCOTA_API_URL, this API's public http(s) origin",
            ))?;
        let redirect_urls: Vec<&str> = trimmed(&self.oauth_redirect_urls)
            .map(|list| {
                list.split(',')
                    .map(str::trim)
                    .filter(|url| !url.is_empty())
                    .collect()
            })
            .unwrap_or_default();
        if redirect_urls.is_empty() {
            return Err(ConfigError::Invalid(
                "sign-in providers need NELCOTA_OAUTH_REDIRECT_URLS, the app pages a sign-in may return to",
            ));
        }
        Ok(Some(OAuthConfig {
            api_url,
            redirect_urls,
            google,
            github,
        }))
    }

    pub fn database_config(&self) -> Result<tokio_postgres::Config, ConfigError> {
        tokio_postgres::Config::from_str(self.database_url.expose())
            .map_err(ConfigError::DatabaseUrl)
    }
}

/// Validated auth email settings (see [`Config::mail`]).
#[derive(Debug)]
pub struct MailConfig<'a> {
    pub smtp_url: &'a str,
    pub from: &'a str,
    pub recovery_url: &'a str,
    pub confirmation_url: Option<&'a str>,
    pub magic_link_url: Option<&'a str>,
}

/// Validated provider sign-in settings (see [`Config::oauth`]).
#[derive(Debug)]
pub struct OAuthConfig<'a> {
    pub api_url: &'a str,
    pub redirect_urls: Vec<&'a str>,
    /// Client id and secret of each enabled provider.
    pub google: Option<(&'a str, &'a str)>,
    pub github: Option<(&'a str, &'a str)>,
}

fn client<'a>(
    id: &'a Option<String>,
    secret: &'a Option<Secret>,
    incomplete: &'static str,
) -> Result<Option<(&'a str, &'a str)>, ConfigError> {
    match (trimmed(id), non_empty(secret)) {
        (Some(id), Some(secret)) => Ok(Some((id, secret))),
        (None, None) => Ok(None),
        _ => Err(ConfigError::Invalid(incomplete)),
    }
}

/// An app page that receives a link: the token is appended as the fragment,
/// so the page must not carry one.
fn link_page<'a>(page: &'a str, invalid: &'static str) -> Result<&'a str, ConfigError> {
    let http = page.starts_with("https://") || page.starts_with("http://");
    if !http || page.contains('#') {
        return Err(ConfigError::Invalid(invalid));
    }
    Ok(page)
}

fn trimmed(value: &Option<String>) -> Option<&str> {
    value.as_deref().map(str::trim).filter(|s| !s.is_empty())
}

fn non_empty(value: &Option<Secret>) -> Option<&str> {
    value
        .as_ref()
        .map(|s| s.expose().trim())
        .filter(|s| !s.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The smallest configuration that passes `validate`.
    fn valid() -> Config {
        Config {
            database_url: Secret::new("postgres://u:p@localhost/db"),
            authenticator_password: Secret::new("a-password-of-16+"),
            jwt_secret: Some(Secret::new("a-secret-with-at-least-32-characters")),
            ..Config::default()
        }
    }

    #[test]
    fn body_limit_must_be_positive() {
        assert!(valid().validate().is_ok());
        assert_eq!(valid().max_body_bytes, 2 * 1024 * 1024);
        let zero = Config {
            max_body_bytes: 0,
            ..valid()
        };
        assert!(zero.validate().is_err());
    }

    #[test]
    fn timeouts_and_rate_limit_are_checked() {
        for invalid in [
            Config {
                request_timeout_secs: 0,
                ..valid()
            },
            Config {
                request_timeout_secs: 10,
                statement_timeout_secs: 10,
                ..valid()
            },
            Config {
                auth_rate_limit_per_minute: 0,
                ..valid()
            },
        ] {
            assert!(invalid.validate().is_err(), "{invalid:?}");
        }
        let no_statement_timeout = Config {
            request_timeout_secs: 5,
            statement_timeout_secs: 0,
            ..valid()
        };
        assert!(no_statement_timeout.validate().is_ok());
    }

    #[test]
    fn s3_error_names_each_variable_once() {
        let s3 = Config {
            storage_backend: StorageBackend::S3,
            ..Config::default()
        };
        let message = s3.validate_storage().unwrap_err().to_string();
        assert!(!message.contains("  "), "{message}");
        assert!(message.contains("_BUCKET, NELCOTA_STORAGE_S3_ACCESS_KEY_ID"));
    }

    #[test]
    fn secret_never_shows_in_debug() {
        let config = Config {
            jwt_secret: Some(Secret::new("super-secret")),
            ..Config::default()
        };
        assert!(!format!("{config:?}").contains("super-secret"));
    }

    fn with_mail(url: Option<&str>, from: Option<&str>, recovery: Option<&str>) -> Config {
        Config {
            smtp_url: url.map(Secret::new),
            smtp_from: from.map(Into::into),
            password_recovery_url: recovery.map(Into::into),
            ..Config::default()
        }
    }

    #[test]
    fn email_off_or_complete() {
        assert!(with_mail(None, None, None).mail().unwrap().is_none());
        assert!(
            with_mail(Some(""), Some(" "), None)
                .mail()
                .unwrap()
                .is_none()
        );
        let config = with_mail(
            Some("smtps://u:p@smtp.x.com"),
            Some("a@x.com"),
            Some("https://app.x.com/new-password"),
        );
        let mail = config.mail().unwrap().unwrap();
        assert_eq!(mail.recovery_url, "https://app.x.com/new-password");
        assert_eq!(mail.confirmation_url, None);
        assert_eq!(mail.magic_link_url, None);
    }

    #[test]
    fn optional_link_pages_need_smtp_and_a_plain_url() {
        let complete = with_mail(
            Some("smtps://u:p@smtp.x.com"),
            Some("a@x.com"),
            Some("https://app.x.com/new-password"),
        );
        let config = Config {
            email_confirmation_url: Some("https://app.x.com/confirmed".into()),
            magic_link_url: Some("https://app.x.com/signed-in".into()),
            ..complete.clone()
        };
        let mail = config.mail().unwrap().unwrap();
        assert_eq!(mail.confirmation_url, Some("https://app.x.com/confirmed"));
        assert_eq!(mail.magic_link_url, Some("https://app.x.com/signed-in"));

        let fragment = Config {
            magic_link_url: Some("https://app.x.com/in#x".into()),
            ..complete
        };
        assert!(fragment.mail().is_err());
        let without_smtp = Config {
            email_confirmation_url: Some("https://app.x.com/confirmed".into()),
            ..Config::default()
        };
        assert!(without_smtp.mail().is_err());
    }

    #[test]
    fn oauth_needs_complete_clients_and_its_urls() {
        assert!(Config::default().oauth().unwrap().is_none());
        let github = Config {
            oauth_github_client_id: Some("id".into()),
            oauth_github_client_secret: Some(Secret::new("secret")),
            ..Config::default()
        };
        assert!(github.oauth().is_err(), "needs the API and redirect URLs");
        let complete = Config {
            api_url: Some("https://api.shop.com".into()),
            oauth_redirect_urls: Some("https://shop.com/auth, http://localhost:5173".into()),
            ..github.clone()
        };
        let oauth = complete.oauth().unwrap().unwrap();
        assert_eq!(oauth.github, Some(("id", "secret")));
        assert!(oauth.google.is_none());
        assert_eq!(
            oauth.redirect_urls,
            ["https://shop.com/auth", "http://localhost:5173"]
        );
        let half = Config {
            oauth_google_client_id: Some("only-id".into()),
            ..complete
        };
        assert!(half.oauth().is_err());
    }

    #[test]
    fn storage_needs_its_backend_settings() {
        let disk = Config {
            storage_backend: StorageBackend::Disk,
            ..Config::default()
        };
        assert!(disk.validate_storage().is_err());
        let disk = Config {
            storage_dir: Some("/storage".into()),
            ..disk
        };
        assert!(disk.validate_storage().is_ok());

        let s3 = Config {
            storage_backend: StorageBackend::S3,
            storage_s3_bucket: Some("files".into()),
            storage_s3_access_key_id: Some("key".into()),
            ..Config::default()
        };
        assert!(s3.validate_storage().is_err());
        let s3 = Config {
            storage_s3_secret_access_key: Some(Secret::new("secret")),
            ..s3
        };
        assert!(s3.validate_storage().is_ok());
        let s3 = Config {
            storage_public_url: Some("files.shop.com".into()),
            ..s3
        };
        assert!(s3.validate_storage().is_err());
    }

    #[test]
    fn half_configured_email_fails_at_startup() {
        for config in [
            with_mail(
                Some("smtps://u:p@smtp.x.com"),
                None,
                Some("https://app.x.com"),
            ),
            with_mail(None, Some("a@x.com"), Some("https://app.x.com")),
            with_mail(None, None, Some("https://app.x.com")),
            with_mail(Some("smtps://u:p@smtp.x.com"), Some("a@x.com"), None),
            with_mail(
                Some("smtps://u:p@smtp.x.com"),
                Some("a@x.com"),
                Some("app.x.com"),
            ),
            with_mail(
                Some("smtps://u:p@smtp.x.com"),
                Some("a@x.com"),
                Some("https://x.com/#/password"),
            ),
        ] {
            assert!(config.mail().is_err(), "{config:?}");
        }
    }
}
