// Generated by `nelcota types`. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      customers: {
        Row: {
          id: number;
          name: string;
        };
        Insert: {
          id?: number;
          name: string;
        };
        Update: {
          id?: number;
          name?: string;
        };
        Relationships: [];
      };
      items: {
        Row: {
          id: number;
          order_id: number;
          product: string;
          qty: number;
        };
        Insert: {
          id?: number;
          order_id: number;
          product: string;
          qty?: number;
        };
        Update: {
          id?: number;
          order_id?: number;
          product?: string;
          qty?: number;
        };
        Relationships: [
          { foreignKeyName: "items_order_id_fkey"; columns: ["order_id"]; referencedRelation: "orders"; referencedColumns: ["id"] },
        ];
      };
      orders: {
        Row: {
          id: number;
          customer_id: number | null;
          seller_id: number | null;
          status: "open" | "paid" | "shipped";
          total: number;
          meta: Json | null;
        };
        Insert: {
          id?: number;
          customer_id?: number | null;
          seller_id?: number | null;
          status?: "open" | "paid" | "shipped";
          total: number;
          meta?: Json | null;
        };
        Update: {
          id?: number;
          customer_id?: number | null;
          seller_id?: number | null;
          status?: "open" | "paid" | "shipped";
          total?: number;
          meta?: Json | null;
        };
        Relationships: [
          { foreignKeyName: "orders_customer_id_fkey"; columns: ["customer_id"]; referencedRelation: "customers"; referencedColumns: ["id"] },
          { foreignKeyName: "orders_seller_id_fkey"; columns: ["seller_id"]; referencedRelation: "customers"; referencedColumns: ["id"] },
        ];
      };
    };
    Views: {
      order_totals: {
        Row: {
          customer_id: number | null;
          total: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      add: { Args: { a: number; b?: number }; Returns: number };
      open_orders: { Args: {  }; Returns: Database["public"]["Tables"]["orders"]["Row"][] };
    };
    Enums: {
      order_status: "open" | "paid" | "shipped";
    };
  };
}
